### ISSUE TITLE
Bug: `Paragraph blank lines` Not Behaving Uniformly with Different List Indicators and Types

### ISSUE THREAD

**Issue by liangzh-404** [platers/obsidian-linter#1014]
before change:
<img width="195" alt="image" src="https://github.com/platers/obsidian-linter/assets/31941670/838f99b8-a9bc-4462-8867-3930fe227106">
after chagne 
<img width="314" alt="image" src="https://github.com/platers/obsidian-linter/assets/31941670/94a3fb0a-ce8d-4226-8821-3a2a84c392e0">

I personally think that the behavior of an ordered list makes more sense to me.

**Comment by pjkaufman** [comment]
Hey @liangzh-404 . I believe that logic is entirely based on the parser itself. Could you provide the source content and before and after? Spacing matters at the end of each line, so that could cause the discrepancy you are seeing.

**Comment by liangzh-404** [comment]
@pjkaufman test case I used
* abc
	abc
	bb

1. abc
	abc
	bb

**Comment by pjkaufman** [comment]
I took a look at the logic and I see the issue. This logic seems to have been written a ways back before we were properly handling all list types. It seems that it is properly recognizing ordered lists that start with numbers and have a period after them. But it is only looking for list items that start with `- ` or `-	`. So that logic needs to be updated to properly ignore all list items.

**Comment by pjkaufman** [comment]
I believe that I have a simple fix for this since we already have regex to check this exact scenario in one go: `startsWithListMarkerRegex`. I just need to add more UTs to make sure that all list item types (orderd, unordered, and check lists) get accounted for.

**Comment by pjkaufman** [comment]
I have merged in the potential fix. It should be in the next release and on master. Please let us know if there are any issues with either of them. Thanks!
