### ISSUE TITLE
FR: Per-File Rule Adjustment

### ISSUE THREAD

**Issue by Servinjesus1** [platers/obsidian-linter#1033]
# Dynamic Control of Linting Per-File

I would like to request expansion of the existing linter ignore capabilities to cover all possible rules via YAML enable/disable flags in files.

## Current Situation

#968 informed me that there is a syntax for telling Linter to ignore some text: `<!-- linter-disable -->` and `<!-- linter-enable -->`.
I didn't immediately see this in the plugin documentation so if it's not in there I would appreciate it being added somewhere associated with the plugin's general configuration, syntax, features, etc.

However, I don't think this covers all linting rules, for example `file-name-heading`, for which there wouldn't be a specific region of text to exclude from the linter to tell it "hey, don't put the file title in here."

<details><summary>Details</summary>
<p>

**As an example:**
I use Longform to do writing and one problem I have is that if I have the file title as the main header in every file, the conversion gets confused because some files are meant to be subsections, etc. not chapters so having a main H1 in every file, and otherwise enforcing H steps of 1 level at a time can become incompatible between Linter and Longform.

</p>
</details> 

Excluding files by location, ReGeX, etc. may work in my case, and I notice there have been FR's for this, but another option would be YAML tags for enabling/disabling specific features in specific files.

## Implementation Ideas

```
---
lint-enable:
  - file-name-heading
  - headings-start-line
  - force-yaml-escape
  - blockquote-style
    - Style: space
lint-disable:
  - remove-leading-or-trailing-whitespace-on-paste
  - convert-bullet-list-markers
---
```

Since macros are already named, I could envision having their names referenced in the YAML like above. Macros which take options will have to have an associated syntax. Positional sub-lists or keyed sub-objects may be some options.

## Complications

First, having linter settings in the YAML requires consideration of how linter already formats the YAML, let alone parsing it. I guess the idea would be that linter would have to first scan the YAML to apply linting settings, then re-scan to YAML to format it.

Second, linter settings that apply to dynamic user action may be hard to implement (e.g. `remove-leading-or-trailing-whitespace-on-paste` or even `Lint-On-Save` which is not a Macro anyway).

**Comment by pjkaufman** [comment]
Hey @Servinjesus1 , some of these things are already documented/added to the Linter.

For example the range ignore syntax (`<!-- linter-disable -->` and `<!-- linter-enable -->`) is documented [here](https://platers.github.io/obsidian-linter/usage/disabling-rules/#range-ignore).

The ability to disable rules via the frontmatter is also present and documented [here](https://platers.github.io/obsidian-linter/usage/disabling-rules/#yaml-frontmatter).

Essentially the syntax is 
``` markdown
---
disabled rules: [capitalize-headings, header-increment] # all to disable all rules
---
```

As for the ability to enable certain rules in a file via the frontmatter, that is a bit trickier. It could be done, but I am not sure how useful a feature that is overall which is one reason I have not added it yet. If there is a desire for it, it can be added. The closest request I recall that I have seen is for allowing multiple profiles for rules (#555 ).

I see that you mentioned paste methods and commands. Obsidian commands would not be something I would do anything with in the file YAML since that should be controlled by a master ignore list in the Linter settings. As for paste methods, I am not sure if there is any kind of benefit to controlling those from the frontmatter (that may already be possible for disabling them), but maybe you have a use case in mind.

Hopefully this helps clarify a few things.

**Comment by Servinjesus1** [comment]
Yes it does! Thanks, apologies that I missed it in the docs.

Since it's already implemented I don't really think it needs any of the other extensions I thought of, so I'll consider this closed.
