### ISSUE TITLE
Bug: Linter Runs Custom Commands even When All Custom Commands Are Blank

### ISSUE THREAD

**Issue by sisi-sh** [platers/obsidian-linter#1060]
- [x ] I have verified that I am on the latest version of the Linter 1.23.2

## Describe the Bug

Switching between file tabs or panes will momentarily try to open a file in the sidebar and then close it immediately, taking away pane focus

## How to Reproduce

1. Have my config (of note: lint on change, yaml-timestamp) 
2. Have sidebar open (or don't, sometimes it will open on its own
3. Click between two file panes or switch files 

edit: yes the same config on a sandbox with no other plugins does the same behavior

## Expected Behavior

Not for there to be skittish file behavior in the sidebar. That linting (/on change) happens without impacting the user experience in an annoying way. 

## Screenshots

https://youtu.be/yCxhI-YMmJw

## Device

- [x ] Desktop
- [ ] Mobile

## Additional Context

No debug-level logs to be found (watch the vid). 

Attached
- [Console logs from video](https://gist.github.com/sisi-sh/67c7240769a68ee6b8100e75ea8d6537)
- [My enabled plugins list](https://gist.github.com/sisi-sh/969edad6971a8a94cb3254d5b59fd018)
- [My config ](https://gist.github.com/sisi-sh/38873c3aa536f203ad075fa5478ec2e3)

**Comment by pjkaufman** [comment]
Hey @sisi-sh , thanks for mentioning this. It looks like you have a blank custom command which is causing this behavior.

When custom commands exists, there is a need to have a file open in order to run the custom commands. Thus on active file change, which fires after the the active file has changed, I have to open the last opened file in the sidebar to run custom commands.

It seems this is not the first time that users have accidentally created or left a blank custom command in their config as their only custom command which causes problems, so I am guessing I need to have a boolean setup to determine if the custom commands present include any valid custom commands and use that to determine what to do with custom commands since the length is not viable.

**Comment by sisi-sh** [comment]
Oh awesome that did fix it. Thanks!

**Comment by pjkaufman** [comment]
That's good. I will see about handling all blank custom commands.

But using custom commands will create that experience with lint on file change since the previous file has to be the active file in order for the custom commands to run properly.

**Comment by pjkaufman** [comment]
I believe I have a fix for blank custom commands running in the sidebar. However I would like to make it clear that custom commands running in the sidebar is expected when custom commands are present and you have lint on file change enabled.

**Comment by pjkaufman** [comment]
I have gone ahead and merged what I believe should prevent the scenario you saw with the invalid running of custom commands. It should be in master now and go out in the next release. Please let us know if either has a problem.
