### ISSUE TITLE
FR: Ignore hyphens in "Space between Chinese Japanese or Korean and English or numbers"

### ISSUE THREAD

**Issue by RyotaUshio** [platers/obsidian-linter#1072]
Thank you for maintaining this important plugin.

## Is Your Feature Request Related to a Problem? Please Describe.

In the CJK languages, mathematical terms often take the form of `<Latin or Greek alphabet>-<CJK characters>`. For example, "σ-field" is translated into Japanese as "σ-加法族".
Applying the rule [Space between Chinese Japanese or Korean and English or numbers](https://platers.github.io/obsidian-linter/settings/spacing-rules/#space-between-chinese-japanese-or-korean-and-english-or-numbers) to `σ-加法族` or `$\sigma$-加法族` results in `σ- 加法族` or `$\sigma$- 加法族`.

However, **there should not be a whitespace between the hyphen `-` and `加法族`**, i.e. those terms should be kept untouched.

## Describe the Solution You'd Like

It would be great if there were an option that does not treat hyphens as English characters.

Example:

Before
``` markdown
English日本語
English-日本語
```

After
``` markdown
English 日本語
English-日本語
```

## Describe Alternatives You've Considered

None

## Additional Context

None

**Comment by RyotaUshio** [comment]
@pjkaufman Thank you for your attention. To be honest, I'm not sure about the exact reason.
But I'm pretty sure that at least 99% of us Japanese use half-width hyphens `-` instead of the full-width `−` in this situation.

One reason I've come up with is that the full-width hyphen is much harder or more tedious to type than the half-width hyphen.
This is due to our keyboard layout and the nature of Japanese IMEs.
In my quick test, the full-width one requires 7 keystrokes while the half-width one requires only one.

**Comment by pjkaufman** [comment]
Hey @RyotaUshio , do you think it would make sense to expose the punctuation/symbol list for English letter symbols to check for  around the CJK characters?

For example, right now that logic lives here: https://github.com/platers/obsidian-linter/blob/416f37f34d7e7170fbb4d1af0868913131b7044b/src/rules/space-between-chinese-japanese-or-korean-and-english-or-numbers.ts#L26-L42.

Essentially there are two sets of punctuation that are looked at:
- Punctuation/symbols before CJK that are considered to be English: `-+'"([¥$]`
- Punctuation/symbols after CJK that are considered to be English: `-+;:'"°%$)]`

_Note: I think `*` is also checked for, but I think I would keep that hidden since it is a part of a markdown syntax check which could get hairy to try to allow the user to customize._

I can expose these two values as a list of characters to consider to be English when they are found in their respective locations. This would also fix #1036 .

How does that sound? Any suggestions around this?

**Comment by pjkaufman** [comment]
A dev note: I will need to handle an empty list to make sure that we do not end up with an empty capture group since I think that is invalid in regex. So I need to handle that to make sure someone does not hose the linter's ability to run by doing that.

**Comment by RyotaUshio** [comment]
By "expose" do you mean adding a setting to customize the list?

**Comment by pjkaufman** [comment]
Yes. Sorry. I forgot to say that it would be a user setting that would be a text box with all of those characters in it that could be edited. It is not a list in the way it would be displayed in the UI.

**Comment by pjkaufman** [comment]
I think I have the code ready for this kind of change, but I need to test in Obsidian and with a couple of edge cases to make sure it does not die. Once I do that, I will go ahead and see about making the change. But if you want to give feedback on what I have written above, feel free to do so.

**Comment by RyotaUshio** [comment]
Thanks for elaborating, it sounds great! I really appreciate your quick work 🙏

**Comment by pjkaufman** [comment]
No problem. Today I am trying to knock out some issues and requests before I do the next release and start focusing back on better handling of mass linting operations.

**Comment by pjkaufman** [comment]
I have merged the change in question. It should be on master and go out in the next release. It looks to be working, but there may be some issues with it. Feel free to let us know if there are any issues.
