### ISSUE TITLE
Bug: "Preserve existing aliases section style" should check Linter's array section style setting to avoid >1 lint

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#1085]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

With "Preserve existing aliases section style" enabled, Linter first adds the alias between the empty `aliases`'s square brackets on first lint, then on the second, styles `aliases` as a multi-line array. Since Linter knows aliases is set to be styled as a multi-line array, it presumably should be able to style the array correctly in one step.

## How to Reproduce

``` markdown
aliases: []
```

1. Change filename (or H1).
2. Lint.

``` markdown
aliases: [Filename]
```

3. Lint again.

``` markdown
aliases:
  - Filename
```

## Expected Behavior

On first lint, produce the second codeblock above.

## Screenshots

**Array multi-line setting:**

![Obsidian_2024-05-04_13-47-29](https://github.com/platers/obsidian-linter/assets/25013746/319abfde-e351-4297-97ae-e4f4dd52d7f3)

**Array multi-line setting:**

![Obsidian_2024-05-04_13-47-57](https://github.com/platers/obsidian-linter/assets/25013746/0fe06b6b-e9da-4556-b34a-73bb3d992027)

**"Preserve existing aliases section style" setting:**

![Obsidian_2024-05-04_13-46-50](https://github.com/platers/obsidian-linter/assets/25013746/a1f3e730-f93f-4626-8cc8-367e61c57f91)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @redactedscribe . I am not sure I 100% follow the issue here. I can see that it is not formatting things as a multiline array on the first lint, but that seems to make sense to me personally. The reason why things look odd is because of how properties works (see #876). Essentially, an empty mutli-line array according to properties is `[]`. In order to accommodate that, the Linter has to assume that an empty multi-line array is `[]`. This means that when you get to `YAML Title` alias you are working with a single-line array. Thus when the value is inserted you get a single line array since you have the option to keep the current key type.

I am thinking I can do a check that says if the original array was `[]` go with whatever the default type is.

**Comment by pjkaufman** [comment]
I think the fix for this should not be too hard. I am hoping it will be a simple fix.

**Comment by pjkaufman** [comment]
Looks like the fix was pretty simple. It should be on master soon.

**Comment by pjkaufman** [comment]
The fix should now be on master and it should go out in the next release. Please let us know if there is an issue with either.

Also, thanks for pointing out this inconsistency. I did not realize it had been missed when the changes were made for #876 .
