### ISSUE TITLE
Bug: HTML comment treated as paragraph

### ISSUE THREAD

**Issue by usernotnull** [platers/obsidian-linter#1160]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

I used the plugin Spaced Repetition, which adds an HTML comment below every paragraph that has been revised.
The rule `https://platers.github.io/obsidian-linter/settings/spacing-rules/#paragraph-blank-lines` treats those comments which are added below the paragraph as another paragraph, and adds an extra empty line in between.

## How to Reproduce

Input:
```
Question line 1.
?
Answer line 1.
<!--SR:!2024-07-10,59,310-->




Question line 2.
?
Answer line 2.
<!--SR:!2024-07-10,59,310-->
```

## Current Output

```
Question line 1.
?
Answer line 1.

<!--SR:!2024-07-10,59,310-->

Question line 2.
?
Answer line 2.

<!--SR:!2024-07-10,59,310-->
```
## Expected Behavior

```
Question line 1.
?
Answer line 1.
<!--SR:!2024-07-10,59,310-->

Question line 2.
?
Answer line 2.
<!--SR:!2024-07-10,59,310-->
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by usernotnull** [comment]
I see the issue. 
The plugin I mentioned unfortunately treats these html comments as a way to save the progress. Each html comments must not be separated from its previous paragraph. 
Unfortunately it doesn't make sense to manually add ignore ranges as the comments are automatically generated.
This means the only way to do this is to ignore all files where I want to used Spaced Repetition, which is far from ideal.

Not sure if I should pursue the matter here or open an issue in the other plugin.

Kindly keep this open for longer as I'm on vacation. I'll reply in 2 weeks with what I got from the other plugin as well.

**Comment by pjkaufman** [comment]
One thing you could do is use a [custom replacement](https://platers.github.io/obsidian-linter/settings/custom-rules/#custom-regex-replacements) to try to make it so that that blank line is removed. If I remember correctly, it runs after paragraph blank lines.

So something like the following should do the trick:
| find | replace | flags |
| ---- | -------- | ----- |
| `\n\n<\!--SR:` | `\n<!--SR:` | `g` |

Please test that this does work before committing to its use.

This may need tweaking if you use these questions in blockquotes/callouts.

**Comment by usernotnull** [comment]
Using a custom regex should work since they run after the rules indeed. This seems like the most reasonable solution.
