### ISSUE TITLE
FR: Lint on file change isn't checking whether the file was actually changed

### ISSUE THREAD

**Issue by nonsciencemark** [platers/obsidian-linter#1161]
## Is Your Feature Request Related to a Problem? Please Describe.

I use Linter to set the `date_modified` field in my YAML so that I can keep track of what files I've been working on each day with a dataview query. However the "Lint on File Change" option is a bit misleading, since it doesn't detect whether I've actually changed a file, it just lints when I close the file.

## Describe the Solution You'd Like

Is it possible to have some kind of check to see whether I've actually modified the file and only then run the linter?

**Please include an example where applicable:**

_N/A_

## Describe Alternatives You've Considered

I've tried using the inbuilt metadata (`file.mday`) to make the dataview queries but this fails when I use Sync across devices since it'll return different things depending on which computer I'm using. The Linter "Lint on File Change" seems to be the best solution if it can actually detect the file change.

## Additional Context

_N/A_

**Comment by pjkaufman** [comment]
Hey @nonsciencemark , sorry about the confusion. That name for `Lint on File Change` may need to be renamed to `Lint on Active File Change` to clarify that it only lints the file when the currently active file changes.

Currently there is no feature for linting when a file is modified due to limitations in the Linter. There is a feature request for it [here](https://github.com/platers/obsidian-linter/issues/183). But so far there is a lot of work that would need to be done to get the Linter to the point where it can actually properly run the file lint when a change is made to the file.

Is the expectation that the only rule that would run is the rule to update timestamps or would your expectation be that the whole set of linting rules run after a file is modified? I ask because I could be overcomplicating what users want. It could be that users just want the timestamp rule to run after a certain amount of seconds have passed since the user edited a file.

**Comment by nonsciencemark** [comment]
Hey @pjkaufman gotcha! It's on changing-the-file-you-are-in not changing-the-CONTENTS-OF-the-file-you-are-in. 

For me personally it'd just be the timestamps, but I naively imagined that there existed some check on whether anything has been _modified_ in the file as a way to optimise the execution of the actual linting process (i.e. skip the lint if nothing has changed since the last lint). 

> It could be that users just want the timestamp rule to run after a certain amount of seconds have passed since the user edited a file.

I had envisaged it the same way that e.g. office products work, where when you close something it prompts "hey do you want to save?" except that here you can just define in the settings "yes Mr Linter, always lint when I close a document please".

That said, this is pretty low priority - if I open a file I usually modify it so it doesn't change much for me personally so maybe a name change is enough for clarity? 

Thanks team!

**Comment by pjkaufman** [comment]
I updated the wording on that rule a little, so hopefully it will be a little clearer. But the description will hopefully handle the rest. There is now an option to run the timestamp change after a couple of seconds after the file is modified. This is on master and hopefully will be in a BRAT release soon.

**Comment by nonsciencemark** [comment]
Amazing, cheers!
