### ISSUE TITLE
Bug: "YAML Timestamp" doesn't consistently update 'last modified' property

### ISSUE THREAD

**Issue by greetclammy** [platers/obsidian-linter#1199]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug
The 'last modified' timestamp very often doesn't get updated when it should.

## How to Reproduce
This happens regardless of:
1. Whether file is linted via command, manual save or file change.
2. What "Date Modified Source of Truth" is set to.
3. How much time passed between current timestamp in frontmatter and last file modification.
4. Whether "Update YAML Timestamp on File Contents Update" is set to 'Never' or 'After 5 seconds'. (If the latter, sometimes timestamp doesn't get updated after 5s but gets updated on file lint; sometimes doesn't get updated on neither; sometimes gets updates on both.)

- Vanilla vault w/ only Linter installed and only "YAML Timestamp" enabled.
- Timestamp format: `h:mm:ss`
- Accounting for a debounce the rule appears to have regardless of whether the "Update YAML Timestamp on File Contents Update" is enabled or not, I made sure to wait (anywhere from 5 to 60 seconds) before making subsequent changes to file.

```
Running linter
rules before regular rules: 0.10000002384185791 ms
Running Custom Regex
custom regex rules: 0 ms
Running YAML Timestamp
yaml-timestamp: 0.5 ms
---
date created: 11:41:24
date modified: 1:30:30
---
@@@@@@@
rules after regular rules: 0.7999999523162842 ms
rules running: 0.8999999761581421 ms
```

[linter-config.txt](https://github.com/user-attachments/files/17449939/linter-config.txt)

## Expected Behavior
Consistent 'last modified' property update as advertised.

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context
I'd love to provide concrete examples of when the timestamp change applies and when it doesn't, but after extensive testing, I couldn't pinpoint any clear cause and effect. It seems to work as advertised only sporadically—sometimes half the time, other times not at all. The rule just seems like a big mess. I wish I was more helpful! Please look into it! 🙏

**Comment by greetclammy** [comment]
Bonus mini 'bug' report (that certainly doesn't warrant an issue! but since I'm here... 😅)

There is an extra article in the description of this setting:

<img width="642" alt="Screen Shot 2024-10-20 at 13 40 11" src="https://github.com/user-attachments/assets/ee3c8938-9694-4400-986d-5d8f588f0269">

**Comment by pjkaufman** [comment]
Thanks for reporting this @greetclammy . The wording change should be simple.

> ## How to Reproduce
> This happens regardless of:
> 
> 1. Whether file is linted via command, manual save or file change.
> 2. What "Date Modified Source of Truth" is set to.
> 3. How much time passed between current timestamp in frontmatter and last file modification.
> 4. Whether "Update YAML Timestamp on File Contents Update" is set to 'Never' or 'After 5 seconds'. (If the latter, sometimes timestamp doesn't get updated after 5s but gets updated on file lint; sometimes doesn't get updated on neither; sometimes gets updates on both.)
> 
> * Vanilla vault w/ only Linter installed and only "YAML Timestamp" enabled.
> * Timestamp format: `h:mm:ss`
> * Accounting for a debounce the rule appears to have regardless of whether the "Update YAML Timestamp on File Contents Update" is enabled or not, I made sure to wait (anywhere from 5 to 60 seconds) before making subsequent changes to file.

Some of this is very broad, so I can take a look, but it may take a little time for me to determine what is happening. I will start with the provided settings. I do want to get clarification on a couple of things here though:

- Are you intending to use this rule via the command and X seconds after the last editor update or was that just something where you tested one when the other did not work?

This helps me narrow down the use case here as well as better focus on how to attempt to reproduce first.

- Does using a timestamp format with date information help fix some of the issues?

One thing that could be causing a problem is that you seem to only care about the hour, minute, and seconds of the change (I am not sure if you are using a 24 hour format or a 12 hour format). But either way, you will encounter issues with this format. You might ask why, and the reason is the Linter compares the value in the frontmatter to the value it is trying to update it with in the same format. The format you are using has no date information, so `moment` will assume you are talking about today. This means that if you made the last update at noon exactly. Making an update at noon the next day will not get an updated timestamp since it is within 5 seconds of the last update according to the timestamp used. I do need to look a little more closely at what is going on here because you describe more than just this one issue. But I thought I would point this out just in case this is causing you issues. Also note that if it is a 12 hour format then you will see the same issue for morning vs eveing updates.

> ## Expected Behavior
> Consistent 'last modified' property update as advertised.

Is my understanding correct that you are expecting that when you edit a file after x seconds the frontmatter will have an updated timestamp if the previous timestamp is more than 5 seconds different than the current value present?

This is assuming you are specifying that the frontmatter is the source of truth. If you are saying the filesystem is the source of truth, that may have unexpected results as I did not look to closely at that scenario. Hopefully that scenario is fine though.

> ## Additional Context
> I'd love to provide concrete examples of when the timestamp change applies and when it doesn't, but after extensive testing, I couldn't pinpoint any clear cause and effect. It seems to work as advertised only sporadically—sometimes half the time, other times not at all. The rule just seems like a big mess. I wish I was more helpful! Please look into it! 🙏

Sorry this is such a pain. Dealing with timestamps has been a real pain-point since many users want different functionalities and I personally do not use a date modified. Hopefully whatever the underlying issue is can get ironed out.

**Comment by greetclammy** [comment]
Thank you for bringing this to your attention! To answer your questions:

>Are you intending to use this rule via the command and X seconds after the last editor update or was that just something where you tested one when the other did not work?

The intended use case is w/ settings "Changes in Obsidian" & "After 5 seconds". I explored another settings for the purposes of testing.

>Does using a timestamp format with date information help fix some of the issues?

I realize now, given your explanation, that I should've used my actual timestamp format: `YYYY.MM.DD HH:mm:ss`. I first observed the inconsistent nature of this rule while using it, and only switched to `h:mm:ss` for the purposes of testing (because that was quicker to type I guess? 😅)

>Is my understanding correct that you are expecting that when you edit a file after x seconds the frontmatter will have an updated timestamp if the previous timestamp is more than 5 seconds different than the current value present?

Correct!
<br>
After further testing, I realized that half the problem was in my testing methodology: I had kept modifying the file by inputting a single character but I determined that Linter only considers a file to be modified if at least 2 characters were added or removed (bug or feature?). Now that I modify the files correctly, it appears that "Update YAML Timestamp on File Contents Update" works OK w/ either "source of truth". But if "Update YAML Timestamp on File Contents Update" is OFF & "source of truth" is set to "Changes in Obsidian", the timestamp doesn't get updated at all on manual lint!

**Comment by pjkaufman** [comment]
> > Does using a timestamp format with date information help fix some of the issues?
> 
> I realize now, given your explanation, that I should've used my actual timestamp format: `YYYY.MM.DD HH:mm:ss`. I first observed the inconsistent nature of this rule while using it, and only switched to `h:mm:ss` for the purposes of testing (because that was quicker to type I guess? 😅)

Gotcha. That makes sense.

> > Is my understanding correct that you are expecting that when you edit a file after x seconds the frontmatter will have an updated timestamp if the previous timestamp is more than 5 seconds different than the current value present?
> 
> Correct! After further testing, I realized that half the problem was in my testing methodology: I had kept modifying the file by inputting a single character but I determined that Linter only considers a file to be modified if at least 2 characters were added or removed (bug or feature?). Now that I modify the files correctly, it appears that "Update YAML Timestamp on File Contents Update" works OK w/ either "source of truth". But if "Update YAML Timestamp on File Contents Update" is OFF & "source of truth" is set to "Changes in Obsidian", the timestamp doesn't get updated at all on manual lint!

So it looks like you are referring to two things here. The first is that the Linter only considers a file modified if at least 2 characters were changed in the editor. This may be a bug or just a constraint of knowing when the user has erased all of their changes. I am leaning towards it being an incidental bug that I need to iron out. But I am not yet certain. I definitely need to take a closer look at this.

The second issue mentioned may or may not be an actual issue. That is to say that manually linting a file may or may not yield an updated timestamp if the source of truth is changes in Obsidian. That will depend on a couple conditions:

If the format in the frontmatter does not match the desired format in the desired locale, then it will be updated. If it does, we check the other conditions.

If the Linter has made a change to the file contents, then if the desired timestamp is more than 5 seconds from the current one, it will update the value. Otherwise, it will leave it alone.

From my recollection, without looking at the code again, that is what dictates whether or not the timestamp gets updated.

So if a change was made by the Linter and it was more than 5 seconds after the value in the frontmatter was set to then, that is a bug. But otherwise, that is expected.

**Comment by pjkaufman** [comment]
I am seeing some sporadic issues with 1 character changes not registering as changes. I will look into this a little more. So far I have not really been able to pinpoint any issue with linting a file manually not actually updating a file's date modified if it made a change to the file.

**Comment by pjkaufman** [comment]
I think I found the issue with the 1 character change. It seems I misunderstood how debounce works. It does not automatically get started when I initially create the logic for it. It seems I need to also call the function as soon as I instantiate it to start that x second timer. I will test and see if this is actually the problem with the first scenario.

**Comment by pjkaufman** [comment]
Ok. That seems to have been the initial issue with 1 character getting removed at a time. So I can make a PR for that. Good job with noticing that discrepancy. I am sorry it caused some confusion. I will attach a zip file with the updated `main.js` if you want to see if this resolves some of your issues.

**Comment by pjkaufman** [comment]
Here is an updated `main.js` if you want to see if there are any issues that still persist with the updated `main.js`. It should address the 1 character change issue.

[main.zip](https://github.com/user-attachments/files/17465446/main.zip)

**Comment by greetclammy** [comment]
Thank you for looking into this! Given that my intended use case works just fine (a single character change not being counted as a file modification event is a non-issue for me), I'll hold off until the official update to the Linter!

> The second issue mentioned may or may not be an actual issue. That is to say that manually linting a file may or may not yield an updated timestamp if the source of truth is changes in Obsidian. That will depend on a couple conditions:
> 
> If the format in the frontmatter does not match the desired format in the desired locale, then it will be updated. If it does, we check the other conditions.
> 
> If the Linter has made a change to the file contents, then if the desired timestamp is more than 5 seconds from the current one, it will update the value. Otherwise, it will leave it alone.
> 
> From my recollection, without looking at the code again, that is what dictates whether or not the timestamp gets updated.
> 
> So if a change was made by the Linter and it was more than 5 seconds after the value in the frontmatter was set to then, that is a bug. But otherwise, that is expected.

I tested this just now and you are correct on all counts. Except when I modify a file, the Linter doesn't update the timestamp! [The wiki states](https://platers.github.io/obsidian-linter/settings/yaml-rules/#yaml-timestamp):

> When a value is present in the frontmatter for date modified, date modified is kept as is unless **the user** or the Linter makes a change to the file

**Comment by pjkaufman** [comment]
Gotcha. Could you elaborate on what you mean by updating the file here? I want to make sure I follow exactly what you are doing that does not work.

I think I am misunderstanding something on my end. The wording may need updating on the wiki/documentation to be more precise on what is meant by a file update. It should just be a contents update that has a change recorded in the YAML timestamp. But it is possible there is an issue there.

If you are updating the file contents via the editor (that is also important because scripts or other things making changes are not visible to the Linter unless they modify the editor directly), then can you set the Linter log level to trace in the debug tab of the settings and do the update again and see what the Linter logs there after your specified time range for when the Linter will try to update the timestamp?

It should log that there either was no change in the notes contents or that an update was made. If it logs neither, then the Linter did not see the change to the files contents.

**Comment by greetclammy** [comment]
>Could you elaborate on what you mean by updating the file here?

Any change I make to the file in the editor (inputting or removing two or more characters) that doesn't trigger any other Linter rules. This currently doesn't result in timestamp update on lint. 

If a rule is triggered on lint i.e. the Linter modifies the file then the timestamp _does_ get updated.

If I set "source of truth" to "File system" OR "Update YAML Timestamp on File Contents Update" to "After x seconds", when I modify the file in the editor i.e. input or remove two or more characters, it results in timestamp update, even if no other Linter rules were triggered. (And that's the intended behavior, no? 🤔 I certainly want the timestamp to get updated when a file is modified in any way--whether by me, the Linter or both.) One would expect it to work the same w/ "source of truth" set to "Changes in Obsidian".

[trace-log.txt](https://github.com/user-attachments/files/17475448/trace-log.txt)

**Comment by pjkaufman** [comment]
> > Could you elaborate on what you mean by updating the file here?
> 
> Any change I make to the file in the editor (inputting or removing two or more characters) that doesn't trigger any other Linter rules. This currently doesn't result in timestamp update on lint.
> 
> If a rule is triggered on lint i.e. the Linter modifies the file then the timestamp _does_ get updated.
> 
> If I set "source of truth" to "File system" OR "Update YAML Timestamp on File Contents Update" to "After x seconds", when I modify the file in the editor i.e. input or remove two or more characters, it results in timestamp update, even if no other Linter rules were triggered. (And that's the intended behavior, no? 🤔 I certainly want the timestamp to get updated when a file is modified in any way--whether by me, the Linter or both.) One would expect it to work the same w/ "source of truth" set to "Changes in Obsidian".
> 
> [trace-log.txt](https://github.com/user-attachments/files/17475448/trace-log.txt)

Ok. I think I see the issue now. I need to add some clarification to the information provided about the source of truth. So when the source of truth is listed as "Changes in Obsidian", you will need to enable "After x Seconds" in order for the Linter to keep the timestamp update. That is an oversight on my part. I just assumed that all users would use those two settings together or only care about the value updating when the Linter made changes to the note's contents. I can add a wording update/documentation change that explains that in order for changes not made by the Linter to be captured as timestamp updates you must enable "After x Seconds" and have it set to the desired timeframe.

Hopefully that clears up the confusion here.

**Comment by greetclammy** [comment]
Dang, that _is_ confusing! But I see now. The wording needs to be altered for sure.

**Comment by pjkaufman** [comment]
Yeah. I will update that description to include a note to explain that other setting is necessary if you want user edits to be captured as a timestamp update.

If that gets added, does that resolve this issue reported here?

**Comment by greetclammy** [comment]
Yep!

**Comment by pjkaufman** [comment]
The wording change has been added to master, but it has not gone live on the website for the Linter. It should be visible after the next release.
