### ISSUE TITLE
Bug? Linter creates a bunch of empty lines

### ISSUE THREAD

**Issue by mtomas7** [platers/obsidian-linter#1225]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Perhaps it is not a bug, but I cannot find settings how to remove this behavior. I set to be only one space between lines, but in this case it creates multiple lines:

![image](https://github.com/user-attachments/assets/e2dff5cb-bac1-4137-b2f0-47ae6106c318)

``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  
  
If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  
  
```

Thank you!

**Comment by pjkaufman** [comment]
@mtomas7 , could you provide your `data.json`. It looks like you may have two conflicting rules enabled or at least two different formats you are using.

It looks like you are ending a line with two spaces. This means add a line break here in markdown. But then you have an empty line. Typically that is not how you would want to do things. Based on your statement, it does not seem you intend to do this. Do you have `Paragraph Blank Lines` enabled? I ask because that would add a blank line before and after each paragraph according to the AST (Abstract Syntax Tree). This is the most likely culprit.

**Comment by pjkaufman** [comment]
Also note, that you have lines with spaces on them which count as non empty lines to the parser if I recall. The Linter does not create those empty lines like that from my understanding. If it does, I would be happy to look into removing it since that really seems like it would be a bug. But if you remove those lines that are just two spaces (or just cut them down to an empty line with no spaces on them), I believe your problem will go away.

**Comment by mtomas7** [comment]
That sample text:

```
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  
  
If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  
  
```

After linting becomes:

```
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).



If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.



```

![image](https://github.com/user-attachments/assets/b9827a1d-49e7-472b-9fbc-f16400326d27)

[data.json](https://github.com/user-attachments/files/17778361/data.json)

**Comment by mtomas7** [comment]
I'm not sure how linter works, but I imagine that it does several rounds and on the last round it would see that there are 4 line breaks and remove a number of them to leave only 1 empty line between paragraphs.

**Comment by pjkaufman** [comment]
So, the issue I am seeing is with `Paragraph Blank Lines`. When you run the Linter with the initially provided text which is
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  
  
If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  
  
```

Note that you have two lines that are made up of two spaces `  `. This means it is a markdown paragraph whether that is the intent or not may be another story.

So with the rules enabled it results in the following:
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).



If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.

  
```

Which you pointed out prior. Here are the logs that are in the console if you set the Linter's log level to trace:
```
[Obsidian Linter] Running linter
plugin:obsidian-linter:43 [Obsidian Linter] rules before regular rules: 0.09999999776482582 ms
plugin:obsidian-linter:43 [Obsidian Linter] Running Remove Multiple Spaces
plugin:obsidian-linter:43 [Obsidian Linter] remove-multiple-spaces: 1.3999999985098839 ms
plugin:obsidian-linter:43 [Obsidian Linter] To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  
  
If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  
  
plugin:obsidian-linter:43 [Obsidian Linter] Running Consecutive blank lines
plugin:obsidian-linter:43 [Obsidian Linter] consecutive-blank-lines: 0.7999999970197678 ms
plugin:obsidian-linter:43 [Obsidian Linter] To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  
  
If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  
  
plugin:obsidian-linter:43 [Obsidian Linter] Running Empty Line Around Code Fences
plugin:obsidian-linter:43 [Obsidian Linter] empty-line-around-code-fences: 0.3999999985098839 ms
plugin:obsidian-linter:43 [Obsidian Linter] To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  
  
If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  
  
plugin:obsidian-linter:43 [Obsidian Linter] Running Paragraph blank lines
plugin:obsidian-linter:43 [Obsidian Linter] paragraph-blank-lines: 0.6999999992549419 ms
plugin:obsidian-linter:43 [Obsidian Linter] To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  

  

If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  

  
plugin:obsidian-linter:43 [Obsidian Linter] Running Custom Regex
plugin:obsidian-linter:43 [Obsidian Linter] custom regex rules: 0.4000000022351742 ms
plugin:obsidian-linter:43 [Obsidian Linter] Running Trailing spaces
plugin:obsidian-linter:43 [Obsidian Linter] trailing-spaces: 1 ms
plugin:obsidian-linter:43 [Obsidian Linter] To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).



If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.


plugin:obsidian-linter:43 [Obsidian Linter] rules after regular rules: 2.300000000745058 ms
plugin:obsidian-linter:43 [Obsidian Linter] rules running: 9.5 ms
```

This indicates to me that things ran as expected. If you run it again, you will see those empty lines get removed by consecutive blank lines:
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).

If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.
```

Note that the lines that had two spaces on them were removed `  `.

So this is not exactly a problem with the Linter. It worked how I would expect based on the underlying Markdown. However I am open to ideas on how to make this clearer or work better.

The only two improvements that I can see making based on the above are as follows:
1. Have Consecutive Blank Lines run after the regular list of rules.
  - This would have made it so you never say the issue with the markdown formatting in the first place due to the blank lines with `  ` as their content
  - This is an easier and more sensible change to make
2. Have Paragraph Blank Lines disregard lines that are completely made up of whitespace since that is not really a paragraph
  - This is a much harder change and likely would not have fixed your issue because right now how Paragraph Blank Lines works is that each line is a paragraph unless it ends in two spaces, `\`, `<br>` ,or `<br/>`. In your case, each line ended with `  `, so that would have made things tricky.

@mtomas7 , what are your thoughts on this?

**Comment by mtomas7** [comment]
Just to be sure that I'm not super demanding person :) I installed Prettier on VS Code and on file save it removed those extra line breaks. This shows that this behavior is something most coder would expect by default.

It looks that Option 1 would add this "cleanup round" and if that works, then perhaps that's the way to go ;)

**Comment by pjkaufman** [comment]
I can see about option 1.

My only concern with comparing the Linter to Prettier is I am not sure if it is actually ignoring the markdown that says you want a line break or if they do have a multiple empty lines cleanup that happens at the end.

**Comment by pjkaufman** [comment]
@mtomas7 , so this seems to hit a bit of an edge case that there is no good way I can see of fixing without an edge case. Moving the consecutive blank line cleanup to pretty much the end of rules running results in the following result:
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).

If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.


```

Now you might have noticed that there are two blank lines there at the end of the file. The reason is as follows:
When paragraph blank lines ran it added a blank line after the paragraph text, but before the line with two spaces in it (it is indeed a paragraph as far as Markdown is concerned and there is no way to know if this is mistaken or intentional on the part of the user).

Thus you get the following:
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).  

  

If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.  

  
``` markdown

Then the trailing spaces are removed as prescribed by that rule which results in:
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).



If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.


```

So when Consecutive blank lines runs it cuts out all of the extra lines in the middle and remove a line at the end resulting in:
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).

If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.


```

This leaves only 1 blank line at the end of the document. However if you lint the file again, you will see that the result becomes
``` markdown
To establish a connection to network shares, you'll need to ensure that your device is connected to either UIC VPN (if working remotely or via WiFi) or the local network (if on campus).

If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.

```
This is just because of how Paragraph Blank Lines works. It does not allow the ending paragraph to have an empty line after it.

So the problem boils down to this:
- With the initial given input, Paragraph Blank Lines is correctly adding a blank line between `If you're on campus, confirm that you can see a "connected computer" icon on the bottom-right corner of your screen, indicating your connection to the local network.` and `  `.
- Remove Trailing Spaces then removes `  `
- Consecutive Blank Lines then cuts multiple empty lines down into one empty line
- This leaves a blank line at the end of the file which Paragraph Blank Lines will not allow by default, but due to the order of operations it does exist

I did consider trying to fix things by changing the order of operations, but Remove Trailing Spaces needs to run at the end due to an blockquote styles (see https://github.com/platers/obsidian-linter/pull/945).

Paragraph Blank Lines running after Remove Trailing Spaces is not really possible without breaking current user's abilities to remove the blank line between a paragraph and a heading or other element via custom regex.

So unless I am over-complicating things, this is about as close to remove the blanks in one lint that we will get for the above scenario.

I do plan to proceed with the movement of consecutive blank line removal, but unless you are seeing a logical issue with the above statements then I don't think it is feasible to get this very specific scenario down to 1 lint instead of 2.

**Comment by pjkaufman** [comment]
I have a potential fix ready. I am just waiting to hear back on whether or not I missed something on the other case around `Paragraph Blank Lines` and needing two lints to get the final set of changes that no longer gets changed when the file gets linted again.

I plan to merge the change Sunday if I have not heard anything by then.

**Comment by pjkaufman** [comment]
The fix for this should be merged into master now. Please let us know if there are issues with this on master or in the next release.
