### ISSUE TITLE
FR: Allow for Sorting YAML Keys

### ISSUE THREAD

**Issue by BlckKn1fe** [platers/obsidian-linter#151]
Hi! 

The timestamp will be automatically inserted at the bottom of the front matter. I want it to be shown at the very beginning of the front matter, so I try to add my creat key, which is "creation date", and my modified key, which is "last modified", in `Text to insert`
```
creation date:
last modified:

title:
categories:
tags:
```

When I press Ctrl+Alt+L, it will only update the "last modified"

![image](https://user-images.githubusercontent.com/48120444/146381739-044f8b66-b3c2-46ce-8c3d-8046f638e2cd.png)

**Comment by BlckKn1fe** [comment]
Or, is there any way we can trigger the script of the Templater plugin in Linter?

**Comment by BlckKn1fe** [comment]
Also, "Compact Yaml" does not work

**Comment by pjkaufman** [comment]
I do not believe that the linter is designed to enforce the order of the yaml frontmatter. It could be done, but I do not believe that is the intended use of the linter at this time though it may be added down the road.

When you say "Compact Yaml" does not work sometimes, could you provide an example or 2 so that I might be able to take a look and see about fixing the scenarios in question, @BlckKn1fe ?
