### ISSUE TITLE
Linter doesn't work if front matter contains internal links, like "companies::  [[Company 1]], [[Company 2]]"

### ISSUE THREAD

**Issue by andrey-manakov** [platers/obsidian-linter#155]
No reaction on command to lint in example below
(if line with "companies" is deleted, it starts working) 
```
---
aliases: 
tags: proposal
created: Monday, January 3rd 2022, 12:27:33 am
modified: Thursday, January 6th 2022, 12:25:32 pm
companies::  [[Company 1]], [[Company 2]]
---
```

**Comment by platers** [comment]
The YAML parsing is brittle, its confused about the value of companies, it should work if you change it to `companies:  [[[Company 1]], [[Company 2]]]`. It just doesnt recognize lists in that format

**Comment by pjkaufman** [comment]
@andrey-manakov , have you had a chance to convert your YAML frontmatter to a valid YAML array?

If for some reason the above is valid YAML, please let me know, but otherwise I am closing this with a won't fix label since accommodating invalid YAML is not what this is designed to do. If you would like a rule added to fix this in the YAML frontmatter, we may be able to do so. However, I do hope you have found a good solution to this problem.
