### ISSUE TITLE
[Request] Ignore spaced lines after headers in case of flashcards

### ISSUE THREAD

**Issue by dummifiedme** [platers/obsidian-linter#164]
I use spaced repetition plugin and many times there are headers followed by `#flashcard`.

```
# This is a question
#flashcard
This is a answer
```

Also, tthere is another rule which makes exactly one line before and after paragraph. 

If there could be a special ignore rule, then it would be really helpful :)

**Comment by pjkaufman** [comment]
@dummifiedme , is there a reason you could not disable the rules that are causing the spacing issues for you for the files you are adding the flashcards to? 
https://github.com/platers/obsidian-linter#disable-rules

**Comment by pjkaufman** [comment]
@dummifiedme , I have not heard back from you and wanted to see if there were no work around like disabling the rules in question in the files that have the flashcards before I decide to take any kind of action on this.

If I do not get clarification, I do plan to close this issue since it will be hard to work on this without better understanding why a rule exception would be needed here.

Thanks for helping make this plugin better through suggestions!

**Comment by pjkaufman** [comment]
I am going to close this since I did not get a response about how this relates to disabling rules and whether disabling rules could fix the issue with flashcards being reformatted or if this is still a desired feature.

I am not fully aware of what plugin is being referenced that creates flashcards this way, but it could be feasible to implement this if I were provided more information like the format of a flashcard. So far all I have to work with is a header followed by the tag `flashcard` but no specification on how many lines after that are a part of the flashcard or how to tell that (the plugin in question may specify that in their documentation).

Please feel free to reopen this issue if there is still a desire to have this added to the plugin. Thanks again for helping out by making this plugin better
