### ISSUE TITLE
Rule suggestion: Sort YAML attributes

### ISSUE THREAD

**Issue by platers** [platers/obsidian-linter#170]
#160 #167

Seems hairy to figure out the logic of attribute placement in every yaml rule, would be nice to have a rule that can sort attributes. This way it can be applied to every document.

Simplest option is to sort alphabetically.
Should also have an option to specify the order of attributes manually in a text box.

**Comment by alanalvarado** [comment]
This would be very useful.

im currently using yq to sort them
yq -i -f process 'sort_keys(.)' FILE

**Comment by chumido98** [comment]
> 

how to do that?

**Comment by chumido98** [comment]
> This would be very useful.
> 
> im currently using yq to sort them `yq -i -f process 'sort_keys(.)' FILE`
how to do that? can you guide me?

**Comment by andrewcrook** [comment]
I think there should also be an area that lists all attributes collected by scanning the vault and from previous linting single files.  Then allows you to order them accordingly to the user's preference.

**Comment by pjkaufman** [comment]
This is what I am thinking around sorting YAML:

- There will be a text box that will allow you to set priority
- Anything not in the text box will have a boolean option that lets you specify that they go before or the values in the text box
- Anything not in the text box should be sortable (if boolean option for it is on)
  - Should have options of alphabetical, reverse alphabetical

Please let me know if there is something I am not considering. I see a request to scan yaml keys which may be feasible, but that would have to be a later feature since that seems more complex.
