### ISSUE TITLE
Feature Request: Lint files in folder

### ISSUE THREAD

**Issue by lguenth** [platers/obsidian-linter#177]
Hi, I *really* like this plugin!

Something that I think would be cool is the ability to linter specific folders, e.g. by integrating it into the right-click menu in the file explorer.

Thanks for developing this!

**Comment by pjkaufman** [comment]
This looks like a good issue to tackle. I will see about taking a stab at it this week since I would like to be able to do this kind of thing on my notes in bits, but not just one file at a time. Here is how kanban is doing this: https://github.com/mgmeyers/obsidian-kanban/blob/main/src/main.ts#L239-L251

**Comment by platers** [comment]
maybe look at #33 for reference

**Comment by pjkaufman** [comment]
> maybe look at #33 for reference

That should give a base for how to run the command. I will have to `console.log` to see how to get folder info.

**Comment by pjkaufman** [comment]
I think I have something working. I will see about pushing it on up here. I do have several questions regarding it since I am very new to using typescript and React, so I want to make sure that there was not a better way to have it lint the contents of the folder.

**Comment by pjkaufman** [comment]
Here is the associated PR: https://github.com/platers/obsidian-linter/pull/199 
It may be considered a mess, so please let take a look and let me know about any changes you might want @platers .
