### ISSUE TITLE
FR: Auto run the linter after X minutes since last edit

### ISSUE THREAD

**Issue by beaussan** [platers/obsidian-linter#183]
Add a option to run this plugin automatically after no more edit were made to a file after X minutes.

This will enable the updated / created timestamps to be always up to date, it's easy to forget to manually save a file, and thus, not having the keys updates

**Comment by LeslieP-TX** [comment]
Would love if the "updated" timestamp could automatically run based on a configurable time delay. That's really the only linter function that would need to be run on a continuous basis i think.

**Comment by pjkaufman** [comment]
Copied from #188 

I have a branch that I am working on the changes for this on. It is a proof of concept that kind of works and has some issues to be ironed out. I am going to use this FR as the one I add the notes to for it since there are a lot of these FRs that have been added.

Right now here is what I foresee being done for this feature:
- When a user edits a file, if they have not edited the file for x seconds/minutes (5 seconds, 30 seconds, 1 minute, or 5 minutes), the file will be Linted
- This will not affect any of the mass linting operations as it will be turned off for any changes that happen during that time
- When a file changes after a file is edited, the previous file will still be linted, but it will not display the characters changed display

Things to consider still:
- How does linting the current file work in conjunction with this autosave functionality (if an autosave is scheduled and the current file is linted manually can I cancel the autosave that is scheduled)?
- How do I handle settings updates for the time frame in which the autoupdates will happen? If there are existing autosaves scheduled, can they be updated or will they just run when they run?

Dev Notes:
- The proof of concept needs to swap the debounce function to use Obsidian's
- There needs to be a flag added for when to actually ignore the debounce action added
- There needs to be a way to handle debounces for each file that is manually edited during a set time period (it seems like [WeakMap ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) may be the way to go on that for associating the restraint and cancelling the autosave

**Comment by pjkaufman** [comment]
I have started some work on this, but it is a decent bit more complex than I would like it to have to be in order to run the Linter after editing a file has completed. It may not be in the next release, but I will continue taking a look and working on this.

In the meantime, it may be useful to use the new rule for linting the file when it is closed or when you swap which file you are focused on (see #188 ).

**Comment by pjkaufman** [comment]
Based on the following, I am going to take a stab at this this weekend. I hope to have an experimental feature created, but I can make no guarantees.

> Would love if the "updated" timestamp could automatically run based on a configurable time delay. That's really the only linter function that would need to be run on a continuous basis i think.

The main issue I see happening is that if a user edits a file and then undoes the change, the assumption is that the user did indeed make a change, so the date modified will be updated. Would that be expected behavior?

**Comment by chmac** [comment]
I think if an action is undone, in an ideal world, the timestamp change would also be undone. But I also think it's perfectly acceptable that an undo still results in a new timestamp. It will result in a new modified time on the file system I guess.

**Comment by pjkaufman** [comment]
Yeah. It is just something where I am not sure if there is a way to determine if a change was made. It may be feasible to get the editor text as it was and compare it to what it is when the linting runs, but that is best I can think of for allowing that to work.

So far I have just gotten the setting and basic code in place for this, but I still need to get the denouncing and file by file changes handled. Hopefully it won't be too bad.

**Comment by pjkaufman** [comment]
I just merged the change for this into master. It has options for 5, 10, 15, 30, and 60 seconds after a file is changed. I will try to get a BRAT release out there to get feedback on this feature, so be on the lookout for that.
