### ISSUE TITLE
Message about characters added / removed for date modified → exclude dynamic values?

### ISSUE THREAD

**Issue by 0xlevel** [platers/obsidian-linter#186]
For an otherwise unchanged markdown, I get a notification after save / lint completion, that some characters (e.g., 4, 2, 1, 0) have been removed and added. My guess is, that this refers to the dynamic value of `date modified` set by the linter itself.  

While this is technically correct, it might be a bit confusing confusing/distracting. I’d like to suggest to an option to exclude these parts of the yaml can be ignored and to just display a feedback that the lint worked (L-okay) but nothing changed.

**Comment by pjkaufman** [comment]
The date modified portion of the yaml currently has a bug (#221) where date modified is always changed regardless of whether anything changed in the file.

Would making it so that `date modified` no longer has the issue with updating even though the file has not changed fix this issue as well or were you hoping to make the number of changes added to a file optional via a setting?

**Comment by pjkaufman** [comment]
Thinking further on this, I guess the only question is whether or not only updating date modified in the yaml when the file is actually modified satisfies your request or whether you were looking for something else to be done, @0xlevel ?

**Comment by 0xlevel** [comment]
Hi @pjkaufman, thank you for asking. I did not notice any other case, yet. So, yes, it would satisfy my request.  On more general terms, any dynamic field might cause the same situation, but at the moment this is perhaps a YAGNI (non) issue. ;)

**Comment by pjkaufman** [comment]
Sounds good. I will close this then since the code changes that should fix this are on the master branch now. It should go out next release in the next 2 weeks.

Fixed by #225
