### ISSUE TITLE
FR: Allow Locale Specification as Setting

### ISSUE THREAD

**Issue by avillani** [platers/obsidian-linter#214]
hello,
I love the feature that allows me to update the modification date in the yaml with the lint command.
However, I cannot change the language used in the date (I like having the format dddd Do MMMM YYYY HH:mm ). Whatever I do - obsidian language itself, calendar plugin override, even switching the OS language - I get the date in English, and I would like it in French. I use French locale as well to get the "correct" week number (ISO vs google, etc)
This is a problem, especially since I use the templater plugin to find modified notes based on this.
Am I missing something, or is this not just possible for the moment ?

thank you

**Comment by pjkaufman** [comment]
In moment, there is a way to do so: https://stackoverflow.com/a/17493350

However, I am not sure how to actually make this a configuration value at this time. I may get a chance to investigate this. Right now this is not too high a priority for me since it is not necessarily a linter rule. But it will be on my radar as a whittle down on the issues.

**Comment by pjkaufman** [comment]
This should be taken care of on master. Please let me know if master or the next release does not fix this issue.
