### ISSUE TITLE
FR: "Heading blank lines" Add Option to Not Add Empty Line At Start of File Or After YAML

### ISSUE THREAD

**Issue by anijatsu** [platers/obsidian-linter#219]
Would it be possible to have an exception for this, either by default or via option?

Example
---
```markdown
---
alias: ['authoughts']
---
# Automatic thoughts
```

**Comment by pjkaufman** [comment]
It is possible, but I am curious what the rationale is behind this. Do you mind providing some rationale @anijatsu ?

**Comment by pjkaufman** [comment]
The fix for this should now be on master and is slated for the next release. Please let us know if for some reason it is not fixed on master or in the next release.

There is a new option that should be available that should allow you to turn off the new line between the Yaml frontmatter and the header.
