### ISSUE TITLE
FR: Obsidian Comment %% Has Empty Lines Added Around It

### ISSUE THREAD

**Issue by StefanoRausch** [platers/obsidian-linter#223]
I have the following section:

```
%%
due-date:: [[2022-06-10]]
%%
```

which gets linted as follows -- the result is not expected or wanted:

```
%%

due-date:: [[2022-06-10]]

%%
```

It would be great if ` Linter ` would respect the comments' styling.

Thank you for considering.

**Comment by pjkaufman** [comment]
Hey @StefanoRausch . Could you attach your data.json file located in your vault under `path_to_vault\.obsidian\plugins\obsidian-linter\`? It would help me with reproducing the scenario.

**Comment by StefanoRausch** [comment]
Hi @pjkaufman, I will upload the file when I am on my laptop.

**Comment by pjkaufman** [comment]
Looks like the issue relates to paragraph blank lines.

**Comment by pjkaufman** [comment]
This should be fixed on the master branch. Please let us know if this is still an issue on master or the next release.

**Comment by pjkaufman** [comment]
@AnnaKornfeldSimpson , if you would like, you can go into the `data.json` and either add or update the `logLevel` attribute to be a value of 1. This should let you have most if not all logs on releoad of the linter plugin.

If you are not using the Obsidian dev tools plugin, I would suggest hitting `mod+shift+i` to open the built in developer tools.

Do note that the ignored multiline comments will not have modifications added to their internal logic,but nothing currently makes sure that they do not get a blank line or 2 spaces get addedd after them. That would likely need modification. Do note that 2 spaces between line content and blank lines between paragraphs are 2 incompatible rules as they both try to modify similar content in two separate ways. It is likely both are modifying the 2nd block comment because the placeholder for the text is still considered part of the content. This can be changed, but that would be a feature request.

**Comment by pjkaufman** [comment]
As for the issue with the second multiline comment not being respected, I will see if that is the case based on the regex matches. Something else might be going on with thag.

**Comment by pjkaufman** [comment]
If I were to guess, this is a bug where ignore replaces the comment with a placeholder and that placeholder is not ignored for adding spaces after it. This causes the check for multiline obsidian comments to fail and thus the lines after paragraphs splits the content up by lines. I will try to confirm this. If I do, I would ask that you create a separate bug since this would be slightly different and I don't want to forget about it.

**Comment by pjkaufman** [comment]
> If I were to guess, this is a bug where ignore replaces the comment with a placeholder and that placeholder is not ignored for adding spaces after it. This causes the check for multiline obsidian comments to fail and thus the lines after paragraphs splits the content up by lines. I will try to confirm this. If I do, I would ask that you create a separate bug since this would be slightly different and I don't want to forget about it.

The assumption above that I made is not correct as to the cause of the issue. Are you using `%%` anywhere else in the file? That could cause the issue if it were to go unmatched.

**Comment by pjkaufman** [comment]
It will jusy tell you what rules ran and in what ordse @AnnaKornfeldSimpson . However that may help. I tend to create a test file and lint that file removing content until I have a small reproducible situation. Then I start turning on and off rules.
