### ISSUE TITLE
FR: wrap yaml strings in quotes as necessary

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#224]
For example, I use a title field in my yaml headers. Books and academic papers commonly include colons. When LINTER encounters this it fails silently - nothing happens (no error notification) but the console shows YAMLException. Simply wrapping the offending text in quotes fixes this.

Matched and unmatched single (') or double (") quotes also cause problems with interpreting the yaml string. Ideally you could recognize those cases and wrap the whole value with the appropriate (opposite) quote mark.

I really love this plugin - it has saved me a TON of time!! Thank you for the work.

ps - my first issue / FR on GH so please excuse any shortcomings

**Comment by pjkaufman** [comment]
Hey @olearydj . It may be a little hard to fix this issue since I will not be able to parse the YAML since it is invalid, but I may be able to add some way to fix this or make the linter print a message when it encounters invalid YAML letting the user know that linting is not possible.

**Comment by olearydj** [comment]
Alerting the user of invalid YAML would be a great addition, even if you are unable to correct the problem I described. Thank you for considering my request @pjkaufman!

**Comment by pjkaufman** [comment]
@olearydj , I can see about adding a rule to put values in quotes if they have a quote (single or double) in it and do not start and end with it or if it has a colon in it. That should not be too bad to fix.

I am also fixing up some of the error message displays to show a YAML error if it exists. I cannot make it very specific, but it will try to show you what the offending issue is. It should always log the error in the console now instead of letting it go uncaught sometimes.

**Comment by pjkaufman** [comment]
@olearydj , this change should go out with the release that I plan to put out this week. I need to do some more testing around #236 and another issue I may have found, but once I am satisfied with either creating issues for them or actually fixing the issues assuming it will not take a super long time, I will see about fixing them.

Please let me know if master or the next release does not solve the problem for this issue.
