### ISSUE TITLE
FR: Move Inline Tags to YAML Frontmatter

### ISSUE THREAD

**Issue by ToUpgrade** [platers/obsidian-linter#246]
request: add a yaml rule described above.

**Comment by pjkaufman** [comment]
Looks like there is some desire to have this added, so I will see about having it added. However it is unclear whether this would just add a copy or actually remove the tags from the text outside of the frontmatter. How would this work @ToUpgrade ?

**Comment by efemkay** [comment]
Want to chime in. I came here looking for this feature, but i would prefer it adds to yaml rather than move. Or perhaps an option to do both in linter settings (to cater for both situation).

In my case, I have tags in my obsidian notes that are published to github pages. I need it to be in yaml for me to use tags summary/archive pages, but i also have workflow in obsidian that places metadata at bottom of the note.

**Comment by pjkaufman** [comment]
Thanks for the feedback! That helps. I was not sure exactly how to proceed with this, but thanks to what has been said, I think I can impliment this.

**Comment by pjkaufman** [comment]
I almost have this ready. I just need to go ahead and add some UTs and add the ability to drop the hashtag in the content of the note after moving the body contents to the yaml tag.

**Comment by pjkaufman** [comment]
This has been added and should be present on master and in the next release which I am looking to release tomorrow. Please let us know if master or the next release does not satisfy this feature request.

**Comment by Calorion** [comment]
I like the idea here, but it needs an exceptions block. Some tags perform specific functions, such as #tasks for the [Tasks](obsidian://show-plugin?id=obsidian-tasks-plugin) plugin.

**Comment by pjkaufman** [comment]
> I like the idea here, but it needs an exceptions block. Some tags perform specific functions, such as #tasks for the Tasks plugin.

If you would like, you can put in a feature request around that.
