### ISSUE TITLE
FR: remove YAML attribute

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#288]
## Is Your Feature Request Related to a Problem? Please Describe.

It would be nice to have the option to remove certain YAML attributes.
Over time, my YAML header gets pretty overloaded with cruft. Rather than manually trimming items as I see them the linter could remove old / unwanted attributes.

## Describe the Solution You'd Like

Just like the add YAML attributes interface, but remove.

## Describe Alternatives You've Considered

Manually removing the items as I notice them and remember to do so.

Thanks for your continued work on this great plugin!

**Comment by pjkaufman** [comment]
This should be present on master now. I plan to do a release later today so the change should be included in that. If you would like the changes for the new release, please make sure you are on the latest version of Obsidian `v0.15.6` since a change made needed that version of Obsidian and would not work on prior versions.

**Comment by olearydj** [comment]
Awesome - thank you. Congrats on the big new release! This plugin is definitely picking up steam - look at all the FRs!

**Comment by pjkaufman** [comment]
It definitely is. Hopefully we can keep up with all of the requests and make it as reliable as possible.
