### ISSUE TITLE
Bug: remove-space-around-fullwidth-characters not working well with lists.

### ISSUE THREAD

**Issue by ben-yip** [platers/obsidian-linter#308]
## Describe the Bug

the `remove-space-around-fullwidth-characters` rule breaks the list markdown syntax on some situations.

## How to Reproduce
before:
``` markdown
- 【list item 1】
- 【list item 2】
```

after:
``` markdown
-【list item 1】
-【list item 2】
```

## Expected Behavior

the `space` should not be removed between the list mark `-` and the full-width character `【` at the beginning of the list-item content.

**Comment by pjkaufman** [comment]
Thanks for reporting this issue @ben-yip. 

Could you explain why fullwidth characters are being used where they do not work with markdown syntax? I am asking because the rule is behaving as expected since it is removing the spaces and knows nothing about markdown syntax itself.

I personally would expect it to remove the spaces in the above scenarios since I am not sure there is an exception to the removal of spacing around fullwidth characters in the general case.

Any clarification on how how this is valid for full width characters would greatly help me.

**Comment by pjkaufman** [comment]
Also, if we are going to ignore that the fullwidth characters need space removed around them, would you expect the same behavior in `block quotes`, and `tables`? I am asking because if this is the case, I may need to go ahead and take care of these scenarios as well if possible.

Thanks for helping make this plugin better!

**Comment by ben-yip** [comment]
Thanks for replying. @pjkaufman 

Personally, I am used to put my thinkings or comments inside a pair of `【】` apart from other content, and I use lists quite often.

When I write something like this:

```
- Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
- Autem eius expedita fugit magnam nisi odit porro sit suscipit totam voluptates.
- 【"Lorem ipsum" is used for testing the appearance of a layout.】
```

I'm expecting a complete list. If the space is omitted by this rule, the last line would end up with a normal paragraph just starting with a character `-` other than a sentence as a list item.

And 'Yes' to the second question you brought up. This behavior is expected to be consistent across `block quotes` and `table`, or any other scenario supports nested lists.

If all the above make sense to you, would there be an extra toggleable switch provided for format rule to support this behavior?

**Comment by pjkaufman** [comment]
I am thinking I could add it as a normal part of the rule, but adding it for `block quotes` and `tables` will just add time to how long it will take.

**Comment by pjkaufman** [comment]
Do note: I am referring to fullwidth characters in `tables` and `block quotes`. If it is handle in `lists`, it will likely handle nesting already.

**Comment by ben-yip** [comment]
Adding as normal part of the rule would be great.

As regards the `block quotes` part, I mean this new behavior should also apply to lists inside a block quote. 😂 I mostly care about lists right now.

**Comment by pjkaufman** [comment]
This should be accounted for with lists. There is no need to account for block quotes as they are syntactically correct with no spaces between it and its content. Tables might be a different story, but that will need to be addressed separately if the need arises.

Please let us know if master or the next release does not fix this issue.
