### ISSUE TITLE
Bug: Duplicate settings for YAML "aliases section style"

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [platers/obsidian-linter#351]
## Describe the Bug

After updating today and looking at "Settings" -> "Linter": 

The new "Format YAML Array" area has a setting "Yaml aliases section style" but there is an existing setting for that in the "YAML Title Alias" area. I did not check which one gets priority if the two are set to different values.

## Device

- [x] Desktop v 1.4.1
- [ ] Mobile

**Comment by pjkaufman** [comment]
I would not call this a bug as the rules are separate. I can add an option to ignore certain keys, but if you use both, they should be set to the same value to keep from cauaing issues.

**Comment by pjkaufman** [comment]
Note priority is based on order. So likely the order you see in the settings is the order they run in with the exception of several that have to run at the start or end to work proprerly.

**Comment by pjkaufman** [comment]
I just remembered that you can shut off the formatting of the `aliases` tag for format yaml arrays. You probably should do that for anyone that is using the yaml title rule as the rules are separate and they might fight with each other.

**Comment by pjkaufman** [comment]
Sorry if the above seems weird as I am still getting over COVID.

**Comment by pjkaufman** [comment]
> Thanks for the prompt response! I will close this as not a bug, but I still think it is a bit confusing to have two settings with exactly the same name.

Gotcha. The reason the settings are similar is because you have to know what way to handle the insertion of the title otherwise it might get added incorrectly. I can update the documentation saying that the two settings probably should not be used together.

Do note, that each overarching opytion like "format yaml arrays" or "yaml title alias" are separate pieces of logic. Thus they work independent of one another.
