### ISSUE TITLE
Is there any positive reason to do `replaceRange` line by line instead of using `transaction`?

### ISSUE THREAD

**Issue by k4a-dev** [platers/obsidian-linter#365]
## Why create this issue
If changes are applied `line by line`, a lot of history accumulates and it is `difficult to undo changes` before lint.
By using `transactions`, lint changes can be combined into a single history, `making undo and redo easier`.

if there is a reason not to use transaction, please let me know. I will keep this change for only personal use.
If nothing, I think it would be more convenient to make it a transaction.

## Proposed change
https://github.com/k4a-dev/obsidian-linter/compare/master...k4a-dev:obsidian-linter:feature_change_with_transaction

This change made all tests pass.

**Comment by pjkaufman** [comment]
I am not sure on that. I am not against make changes on a transaction level for each rule, but doing it as all or nothing seems like it could cause more harm than it helps.

For example, hitting undo to me should undo a rule running rather than all rules running. But I am not the most familiar with this concept of replace range vs. a transaction.

I am open to PRs though.

**Comment by k4a-dev** [comment]
The lint is executed with all rules merged, not per rule.
However, undo execution is not batch for file or rule by rule, but line by line with each replaced line.

|process|unit|
|-|-|
|Lint| Batch for file|
|Undo|Per line|

I think it difficult to use that lint is executed on the file at once, but undo is per line. 

The fact that there have been no similar suggestions seems to indicate that this is just my feeling. I will see how it goes for a few days and close this issue.
