### ISSUE TITLE
FR: Lint on autosave

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#392]
## Is Your Feature Request Related to a Problem? Please Describe.

I use Obsidian primarily on mobile, and therefore executing manual saves is bothersome. 

## Describe the Solution You'd Like

I would like Lint to optionally fire whenever a file is modified and saved. 

## Describe Alternatives You've Considered

[Update time on edit](https://github.com/beaussan/update-time-on-edit-obsidian) purports to do this, but works only sporadically, at least on mobile.

**Comment by pjkaufman** [comment]
This seems similar to https://github.com/platers/obsidian-linter/issues/188, but it is slightly different. I am not sure how often autosave gets run. It could cause issues with the Linter getting into an infinite loop. Would it be better to add the command to the mobile toolbar and use that instead?

Also, would linting on file close or file change make more sense? I ask because of my concern with accidentally causing an infinite loop with the linter if another autosave is triggered by the linter making changes.

**Comment by Calorion** [comment]
File close or change would work fine. I didn't see #188; that would do nicely.

**Comment by pjkaufman** [comment]
I am still looking into whether that is something that fires off an event since I know that I can check the active leaf, but it would be more convenient if I could check run it via a method that checks when you swap the active file for another in the case of swapping to a popout window or changing tabs as in version 16 (which is still in beta).

**Comment by pjkaufman** [comment]
I will close this in favor of #188 .
