### ISSUE TITLE
FR: Remove redundant `linter-yaml-title-alias` when YAML Title Alias is activated

### ISSUE THREAD

**Issue by lguenth** [platers/obsidian-linter#404]
## Is Your Feature Request Related to a Problem? Please Describe.
Hello Victor!
Some people in the OMG Discord tried to troubleshoot the YAML Title Alias feature of your plugin today. 
We found it odd that there is no way to turn off the redundant `linter-yaml-title-alias` key when letting the plugin generate alias(es) from file name or H1. I originally thought that the last settings option "Keep alias that matches the filename" would toggle this behaviour on or off but it doesn't seem to make a difference.

## Describe the Solution You'd Like

**Please include an example where applicable:**
Before
``` markdown
---
tags: 00_inbox/maintenance
type: zettel
created: 2022-05-23
modified: 2022-09-11
---

# Ideen-Scratchpad 💡
```
After (disregarding any quoting/further formatting possible for that array)
``` markdown
---
tags: 00_inbox/maintenance
type: zettel
aliases: [Ideen-Scratchpad 💡]
created: 2022-05-23
modified: 2022-09-11
---

# Ideen-Scratchpad 💡
```

## Describe Alternatives You've Considered
The alternative I considered is not using it although it could be useful. Or writing this up as a bug report and not a feature request. :wink: 

## Additional Context
This is what it currently looks like:
![grafik](https://user-images.githubusercontent.com/69049131/189532392-e81cbb17-982d-478e-bc19-4d0f39b959fb.png)

**Comment by pjkaufman** [comment]
Thanks for the input! As of right now the rule uses that yaml key to determine what alias to replace when a file rename happsns. Without it, it would be unable to do anything about file renames or even H1 changes.

Could you explain whether you expect this rule to just add new values to the alias key on a rename or should it replace the old names as well?

**Comment by pjkaufman** [comment]
I can definitely add the extra linter key as an option for the rule that can be disabled with the caveat that it would not replace the proper value for the old heading or old title.

**Comment by pjkaufman** [comment]
Barring any further information about what the desired functionality is, I will be converting this option for `linter-yaml-title-alias` to an option you can turn on and off. You will lose the ability to remove the old names from the list of aliases when the option for it is turned off. Please let us know if this is not intended @lguenth .

**Comment by pjkaufman** [comment]
I am looking into implementing this, but it seems that this will require a rewrite of the logic since it was taking advantage of several optimizations that were allowed if you were using the extra yaml key to store the old file name. Now with the two versions, things will work slightly differently. I will see about getting this done as smoothly as possible, but it might not be until Friday or Sunday before the change gets added if all goes well. It may push back the addition of the new settings UI as well.

**Comment by pjkaufman** [comment]
It looks like I have it partially working. It just seems to not be working when the aliases key is not already present and maybe a couple of other scenarios. I need to add some UTs for this and make sure it is working fine before pushing it up. It looks like it may benefit from me extracting the logic from yaml format arrays out into its own helper methods and just have those methods be reused by each of these methods. It might standardize things a little and make it so the two options can work in similar scenarios. It would just require making it so that both sets of options can be made to jive with one another since right now they do not do so.

**Comment by pjkaufman** [comment]
This change should be on master now. It will go out with the next release. Please let us know if master or the next release does not allow this value to be optional.
