### ISSUE TITLE
Bug: Two lines around Code Fences.

### ISSUE THREAD

**Issue by jerviscui** [platers/obsidian-linter#456]
## Describe the Bug

Will add two lines around Code Fences.

## How to Reproduce

1. Enable **Empty Line Around Code Fences**
2. Enable **Consecutive blank lines**

## Expected Behavior

Expected output if applicable:

The formatted result:

~~~
``` markdown
1. 修改 php.ini


    ```
    upload_max_filesize = 20M
    post_max_size = 20M
    ```


2. 修改 Nginx 配置文件


    ```
    client_max_body_size    20m; # 文件最大大小
    ```


1111

```
int a = 0;
```

2222
```
~~~

The code block not in the list is correct, it is around with a blank line.
The code block in the list will be around two blank lines. I think the code block around with one line is correct.

## Device

- [x] Desktop

**Comment by jerviscui** [comment]
Oh. I just to show the content of the file, so use the markdown block.

~~~
``` markdown 
~~~

**Comment by pjkaufman** [comment]
I will see about reproducing this tonight and if I can, I will aim to have it done for the next release.

**Comment by pjkaufman** [comment]
Looks like I have a fix for the bug. The issue is that it was trying to match the whitespace of it with that of the previous line which is technically how it was written, but I see that that is not really necessary, so I have gone ahead and removed that part of the logic. This should take care of the problem and will hopefully not create any others.

**Comment by pjkaufman** [comment]
This should be taken care of now. It will be pushed out with the next release. If you would like, you may go ahead and use the master version of the plugin before then.

Please let us know if the issue persists either on master or in the next release.
