### ISSUE TITLE
FR: space between Chinese/Japanese/Korean and English

### ISSUE THREAD

**Issue by iucario** [platers/obsidian-linter#479]
Examples:

```markdown
日本語englishひらがな
カタカナenglishカタカナ
ﾊﾝｶｸｶﾀｶﾅenglish１２３全角数字
한글english한글
```

```markdown
日本語 english ひらがな
カタカナ english カタカナ
ﾊﾝｶｸｶﾀｶﾅ english１２３全角数字
한글 english 한글
```

The original rule only considers Chinese.
https://github.com/platers/obsidian-linter/blob/5624359551750c9adbb7ad67745a69677cf3259d/src/rules/space-between-chinese-and-english-or-numbers.ts#L25
To deal with CJK, we can easily implement this by replacing `[\u4e00-\u9fa5]` with `\p{sc=Han}|\p{sc=Katakana}|\p{sc=Hiragana}|\p{sc=Hangul}`

**Comment by pjkaufman** [comment]
Thanks for this suggestion. I will have to see about adding this to the list of things to do. I am definitely interested in adding it, I just need to see about making sure that it works gets the right updates to map the property since it will need that to happen due to wording changes that will be necessary.

**Comment by pjkaufman** [comment]
There may be a problem adding this because of the Unicode property usage, but we can go ahead and see if that truly is the case once I get through some of the things I am working on.

**Comment by pjkaufman** [comment]
This change has been merged and should be present on master and in the next release. Please let us know if either of these is not the case.
