### ISSUE TITLE
Bug: Linter fails to property delimit frontmatter tags separated by commas

### ISSUE THREAD

**Issue by ScottKillen** [platers/obsidian-linter#509]
## Describe the Bug

If a note's frontmatter contains tags that are delimited by a comma without a trailing space, linter treats them as a single tag.

## How to Reproduce

I have attached the data.json file. [data.json.txt](https://github.com/platers/obsidian-linter/files/10057774/data.json.txt)

### Example 1

include in frontmatter YAML:

`tags: tag1,tag2`

### Example 2

include in frontmatter YAML:

`tags: tag1,tag2, tag3`

Linting the file produces an incorrect result when the tags array is split into a multiline array:

Example 1 produces no result, even though it contains two tags.

Example 2 produces a note that now only contains 2 tags ("tag1,tag2" and "tag3") even though before linting the note contained three tags.

## Expected Behavior

Linter should parse the tags array **exactly** how Obsidian parses the tags array.

Example 1 should produce a multiline tags array with two tags.
Example 2 should produce a multiline tags array with three tags.

## Device

- [x] Desktop
- [?] Mobile

**Comment by pjkaufman** [comment]
Thanks for reporting this issue. I am not sure how to best handle this situation. I don't have access to the exact logic Obsidian uses to parse the YAML, so using it is out of the question in the Linter itself since I need a way to UT this and that would prevent me from effectively and confidently doing so.

I could loosen the standard for all YAML arrays, to break it apart on a `,` instead of `, `, though this could lead to other issues. This will likely need to be tested out.

**Comment by pjkaufman** [comment]
Here is the logic that needs modification for dev reference later: https://github.com/platers/obsidian-linter/blob/master/src/utils/yaml.ts#L193-L199

Hopefully it can be fixed quickly later on today or before the next release.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if this is not the case.

**Comment by ScottKillen** [comment]
Confirmed this is fixed.

Thank you.

**Comment by pjkaufman** [comment]
Good to hear. Hopefully it will go smoothly from here.
