### ISSUE TITLE
Suggestion: Add a toggle switch for each rule

### ISSUE THREAD

**Issue by firinael** [platers/obsidian-linter#51]
Writing down each rule in a box seems unnecessary, and is pretty bad for ease-of-use.

**Comment by chrisgrieser** [comment]
related to #42, since doing a toggle (which I also think is a good idea), implies implementing a default order of execution.

**Comment by platers** [comment]
Yeah, I'll work on this next. 

For my future reference, the reason its a text box now is because 

- I didn't want to figure out rule order
- I thought the settings page would grow too long
- Rule options need more structure, takes a while to implement and unclear requirements
- Didn't bother researching whether obsidian settings have the UI components needed

**Comment by platers** [comment]
Updated UI in latest release, please let me know if you find any issues!
