### ISSUE TITLE
FR: Removes the first and last blank lines inside Code Fences

### ISSUE THREAD

**Issue by cpfy** [platers/obsidian-linter#571]
## Is Your Feature Request Related to a Problem? Please Describe.

Sometimes codes copied from IDE have blank lines around. However, we just need core parts of it.

## Describe the Solution You'd Like

After calling Linter, all unnecessary blank lines in the code block are removed.

**Please include an example where applicable:**

If there are multiple blank lines before and after in a block of code, for example:

``` markdown
    ```python
      
      

    def my_sum(*args):
        return sum(args)
    
    print(my_sum(1, 2, 3, 4))
    # 10
      
      

      
    ```
```


After linting, it will be:

``` markdown
    ```python
    def my_sum(*args):
        return sum(args)
    
    print(my_sum(1, 2, 3, 4))
    # 10
    ```
```


## Additional Context

There are times when empty lines in the middle of a block of code should not be removed, so it is only recommended to remove the beginning and the end.

If there was a way to identify the extra blank lines in the middle of a block of code, this would be really, really great and fantastic! But this may need to be adjusted for different programming languages

**Comment by pjkaufman** [comment]
It looks like this issue is pretty old and has not actually had any other users indicate that they would like this feature. It is currently possible to implement this using [custom regex replacement](https://platers.github.io/obsidian-linter/settings/custom-rules/#custom-regex-replacements). So I am going to close and we can revisit this if there is a need for this by users at a later date.
