### ISSUE TITLE
FR: Do Not Change `Created` YAML Timestamp Key if Date Format Changed and Does not Match Existing Value

### ISSUE THREAD

**Issue by karmeye** [platers/obsidian-linter#621]
## Describe the Bug

Created date overwritten after date format changed. This is unwanted if the file's created attribute isn't correct anymore for whatever reason.

## How to Reproduce

Consider this scenario:

1. Files are created and linted so that the a YAML `created` field is set according to specified date format.
1. Files are moved/copied in a way which resets their created attribute (on file system level), e.g., pulled from git repo to a new device.
2. Linter's date format is changed
3. Linting these files now overwrites the correct YAML `created` date with the file attribute's newer date. So the date is now in the desired format but the actual date is not correct anymore.

## Expected Behavior

Hardest: Try to parse the current date and convert it to the new format. In my case the format changed from YYYYMMDD to YYYY-MM-DDTHH:mm:ssZ. Time component could have been padded with zeros.

Or easier, if the YAML `created` date doesn't match the file's, cancel lint and display error.

Worst case: if format doesn't match  cancel lint and display error.

These are just suggestions 🤔

## Device

- [ probably] Desktop
- [x ] Mobile

**Comment by pjkaufman** [comment]
This is more of  a feature request than a bug as this is actually how it is designed to work and was rewritten to work this way expressly, As such, I am going to update the ticket name and labels to reflect that.

**Comment by pjkaufman** [comment]
The main problem would be around making something robust. The file created at time is different between devices or if a file is copied. So technically this is working correctly when you set the created at time on desktop and then update the date format on mobile or on some other device.

**Comment by pjkaufman** [comment]
The problem is that it is indeed using the file metadata for setting the value of the created date. The change in format only requires it to regenerate the file created date metadata into a valid string. However there are several ways to change the file created at metadata and it is not just these methods:
- copying a file
- moving a file can
- manually updating a file's metadata
- moving a file to a new device (manually or via a sync process)

Thus, the result is correct in that it is updating your file metadata to the file's created at metadata. However your intent is to not change the value at all even if the file metadata has changed for the created at functionality. I recall this being something that was asked for in the past, but I am not recalling which request it is a part of. This should not be too hard, but it may prevent updating the format of the timestamp in the YAML.

**Comment by pjkaufman** [comment]
While I agree with some of the sentiment, I will say that the rule was not designed when syncing was something supported by Obsidian. Thus it was fine to assume that the Metadata was accurate.

I plan to add a boolean to allow you to specify that you want to preserve the value coming from the frontmatter if it exists. The problem with making it the how the rule works without an option is that the file Metadata includes a full timestamp while the value in the YAML does not necessarily do so. This means that if you force the use of the YAML value and it is only specific to the point of hours, a change to a more specific time format will not be correct as that information was not preserved in the YAML.

**Comment by pjkaufman** [comment]
I believe that there are many people who are fine with it being the file metadata which more accurate and easier to use as a way to set the value in the frontmatter. I am working on something for this to allow you to pull the value from the frontmatter, but so far they have not been parsing the value correctly since it does not know what format the data it is being given is in.

I am not sure that I can do what you are saying with the padding of 0s as there is not really a good way to tell programatically if that has happened. There are some scenarios where that may be likely to be the case, but there is no smoking gun from what I can tell.

**Comment by rhhub** [comment]
If I go to my obsidian vault and copy everything and then paste it into another folder all the system created dates change to the current time. Copying is the poorest way to backup your vault but it is an important option. 

I'd like to add to the opinion that a yaml created date should only be tied to a system created date on creation. After that, it should be preserved at all costs because that seems to matter more. In all honesty, it should be a core plugin.

**Comment by pjkaufman** [comment]
The flaw in doing what you state @rhhub is that the desired format for the created date can have 2 flaws in it:
1. It lacks sufficient information to change date formats
  - There is little if anything the Linter can do about this and if a change in format is requested, it may fail or result in bad data being displayed
2. The value placed in the frontmatter may not be a valid date format or be parseable by the Linter without knowing the exact format of the date
  - If it cannot figure out what the format of the date is, it may very well go ahead and force a created at value update

To me this implies that if you want to do backups that require changing the file metadata associated with the file, your only real option is to add a specific option to handle those kinds of changes.

**Comment by pjkaufman** [comment]
I may have found a way to determine the proper date format which will help greatly with this. I just need to make sure it works. Then I can try to clean up some things.

**Comment by pjkaufman** [comment]
Also, I am not sure the proper operation is to throw an error when an issue arises as that will kill the entire lint of the file. The 2 options I have are as follows:
- Add a comment to the YAML explaining that the parse failed (this will break parsing this value in the future)
- Log a warning for the user to be able to see that an issue occurred

I can throw an error, but that prevents linting the file, so that is possible if it is really necessary.

**Comment by pjkaufman** [comment]
Right now I am going the route of logging the info as a warning since errors cannot be displayed without preventing the linting of the file.

**Comment by pjkaufman** [comment]
> > Right now I am going the route of logging the info as a warning since errors cannot be displayed without preventing the linting of the file.
> 
> Can you display the error as a message? In the same way you display a message after linting if "Display message on lint: is set.

I can, but that requires failing to lint the file entirely (it may require you to read a console log).  Is that acceptable? I am unable to send messages from a lint rule to display to the user without failing all lint rules for the file.

**Comment by pjkaufman** [comment]
Each error is logged and linting multiple files will continue continue even if one file throws an error.

**Comment by pjkaufman** [comment]
Looks like the error will get logged in the console. It is possible to view the error by running the lint on the file directly with the lint on save logs setting enabled and then checking the debug tab or going ahead and opening the console log to see what happened.

**Comment by pjkaufman** [comment]
The change for this should now be on master and go out with the next release. Please let us know if that is not the case.
