### ISSUE TITLE
Bug: YAML Timestamp modification date shows current time

### ISSUE THREAD

**Issue by craigeley** [platers/obsidian-linter#628]
## Describe the Bug

The YAML Timestamp rule for date modified seems to always put the current time. 

## How to Reproduce

1. Go to any file
2. Click on 'lint current file' with YAML Timestamp rule enabled
3. See the current time, even if it is different from the system modified time as seen in Finder

## Expected Behavior

Should reflect the time the file was actually modified, as viewable in Finder or Terminal. 

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@craigeley , how far off are the times in question? It is not possible to have the date modified equal the value in the metadata foe rhe file since it would change on save. Thus it uses the current time which should be within about 5 seconds of the new date modified value for the file.

**Comment by craigeley** [comment]
This just felt like unexpected behavior when running "Lint all files in the vault." Some files that I hadn't touched in a while were now all modified immediately, which feels inaccurate. Maybe it should just be stated in this section of the documentation—even though it is kind of obvious now that I think about it—that the modification date will always be the current time, since running the linter modifies the file.

**Comment by aidan-gibson** [comment]
I bumped into the same thing. I have an annoying solution, but it works.
It needs https://github.com/mikefarah/yq (`brew install yq` if you're on macOS)
I use https://github.com/Taitava/obsidian-shellcommands to run the following zsh on the "Switching the active pane" event.

```zsh
# Assumes if there is frontmatter, it will be in the beginning.

# load file metadata before anything; editing the file will change the metadata
date=$(stat -f '%Sm' {{file_path:absolute}} | xargs -I{} date -jf '%b %d %T %Y' '{}' '+%Y-%m-%d %H:%M:%S')


# if no YAML (starting on first line), add it
if ! head -n 1 {{file_path:absolute}} | grep -q '^---$'; then
sed -i '' "1i\\
---\\
modi: $date\\
---\\
" {{file_path:absolute}}
# YAML exists, but no modi:
elif [[ "$(yq -f=extract '.modi' {{file_path:absolute}})" == "null" ]]; then
    sed -i '' "2i\\
modi: $date\\
" {{file_path:absolute}}
# YAML exist and modi: exists, update; commented out as I want to manually run updates to to modi
else 
    # sed -i -E "s/^modi: .*/modi: $date/" {{file_path:absolute}}
fi
```
Just change "modi" to whatever you want your modified file to be.

When I want to update `modi` field, I run the following zsh (assigned to a hotkey via obsidian-shellcommands plugin)

```zsh
date=$(stat -f '%Sm' {{file_path:absolute}} | xargs -I{} date -jf '%b %d %T %Y' '{}' '+%Y-%m-%d %H:%M:%S')
sed -i -E "s/^modi: .*/modi: $date/" {{file_path:absolute}}
```



I love obsidian-linter and use it otherwise but I have it disabled for timestamps.

**Comment by pjkaufman** [comment]
The Linter updates the date modified in the frontmatter when it makes a change to a file, so turning that rule off or at least the part for date modified would be the way to keep that from happening.

Since this seems to have been resolved by realizing that the Linter automatically does update the date modified value when it updates a file, I am going to close this issue.
