### ISSUE TITLE
 Question about whether Github plugin supports random numbers or calling random files in the text to insert section

### ISSUE THREAD

**Issue by nevertoday** [platers/obsidian-linter#659]
Dear developer,
I am a Github user and I have recently encountered a problem while using your plugin. I would like to implement random numbers or call random files from a certain directory in the text to insert section of the plugin's YAML area. For example, I would like to use a random number parameter in the banner parameter. I would like to know if your plugin supports this feature, and if so, I would appreciate it if you could tell me the simplest way to implement it.
Thank you very much for your patience in reading this message. I look forward to your reply.
Thank you!

![image](https://user-images.githubusercontent.com/166048/226182078-0b5186fb-b6e6-481a-98db-8086fdf232f5.png)

**Comment by pjkaufman** [comment]
Hey @nevertoday . I am pretty sure the Linter does not support either of those actions directly, though I am not certain based on the description provided.

Could you give an example or 2 of what you were wondering whether the Linter does in terms of markdown before and after examples along with an explanation of how those changes may have come about (i.e. x value was present in the title thus this happened or x was in the YAML so that happened)?

**Comment by nevertoday** [comment]
I use shell script already ,thks

**Comment by pjkaufman** [comment]
> I use shell script already ,thks

I take it this means we are good to close this. I plan to close this tomorrow if I don't hear otherwise.

**Comment by pjkaufman** [comment]
Looks like we are good to close this so I am doing so now.
