### ISSUE TITLE
FR: Allow `Ordered List Style` to Optionally Update Numbers

### ISSUE THREAD

**Issue by Drakemoor** [platers/obsidian-linter#744]
I'm sorry if that's not the place to ask that kind of question, but I couldn't find any other place to ask. Please excuse me if I'm at the wrong place.

Here is the problem. Linter keeps resetting the numbering of the list items across different headings

I have a list like this:
```markdown
## Title one

1. Item one
2. item two
3. Item three

## Title two

4. item four
5. Item five
```

When I use Linter, it transforms it into:
```markdown
## Title one

1. Item one
2. item two
3. Item three

## Title two

1. item four
2. Item five
```
How can I stop it from doing this?

Im not sure if it's a bug, or if there is an option for this.

**Comment by pjkaufman** [comment]
Hey @Drakemoor , I have encountered similar things myself. With how Markdown works, a list cannot be interupted by any other kind of element. This means that the first 3 ordered list items are in one list while the last 2 are in their own list.

There is no setting for turning off automatic increment of ordered list items asside from not having the rule enabled to begin with: https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#ordered-list-style

It could be possible to add a mode that just leaves the number as is.

**Comment by pjkaufman** [comment]
You could also use ranged ignores on the section in question if you don't want it to be linted, but you do want to keep the rule enabled in general:
``` markdown
## Title one
<!-- linter-disable -->
1. Item one
2. item two
3. Item three

## Title two

4. item four
5. Item five
<!-- linter-enable -->
```
More on ranged ignores can be found here: https://github.com/platers/obsidian-linter#range-ignore

**Comment by Drakemoor** [comment]
It's often natural to start a list, then stop and provide some text that's a meta-comment about the list--without the text being, logically, part of the list--and then continue the list. And I noticed that the option controlling the order is "Ordered List Style". It would be nice if we had the option to still use it but to be able to turn off the "Number Style" sub-option. 

Thanks for your help.

**Comment by jose-elias-alvarez** [comment]
I ran into the same issue, as I also like to break up ordered lists with other content but still want to keep the linter option enabled, since Obsidian’s automatic ordering is pretty wonky. I guess it violates the Markdown spec, but Obsidian itself seems to handle “broken” ordered lists just fine in reading mode:

<img width="136" alt="image" src="https://github.com/user-attachments/assets/cc64100c-d30e-410e-bb7f-716ddd1218bb">

If there’s no objections to including a rule that contradicts the spec, I’m happy to put in a PR. Would you prefer to see this as a separate option or as an additional option for `Number Style`? I’d lean towards the latter and add a new `ascending-broken` option, since it doesn’t really make sense to combine the new option with `lazy`.

**Comment by pjkaufman** [comment]
Hey @jose-elias-alvarez , I would be open to having this added as another option for the style. I personally would prefer to have an option to make it work the way listed here, but ordered lists are broken out separately and modified in reverse to cause as few conflicts as possible when updating the values.

I am definitely open to a PR for this feature.

**Comment by pjkaufman** [comment]
The changes for this should now be in place on master. They should be incorporated into the next release. Please let us know if this is not the case.
