### ISSUE TITLE
Bug: "Linted all files" notification stays forever

### ISSUE THREAD

**Issue by Eejit43** [platers/obsidian-linter#752]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

"Linted all files" notification remains onscreen forever.

## How to Reproduce

Run "Linter: Lint all files in the vault" in the command pallete.

## Expected Behavior

The notifiction should disappear after a short amount of time.

## Screenshots

<img width="210" alt="Screenshot 2023-06-05 at 1 21 47 PM" src="https://github.com/platers/obsidian-linter/assets/76887639/ba5fe841-a4e6-4679-bb21-3dd5e2d82cd5">

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

N/A

**Comment by pjkaufman** [comment]
Thanks for reporting this. However, the ending notifications do not disappear without a user click because of how long they can take. If you would like, a setting could be added for how long a mass limt notification will be on screen after it appears, but I do not plan to make that entirely go away after a couple seconds no matter what.

The reason I do not plan to do that is because the mass lint notifications may get missed otherwise. This is not a problem for small vaults, but for the vault I use, it takes about 4 minutes to lint all files, so I would often moss the notification.

Thus a setting makes sense while making that the behavior for eveeryone does not.

**Comment by pjkaufman** [comment]
If you would like a setting for this, I will gladly add that. It would have options like the notification will disappear:
- On user click
- after 1 second
- after 2 seconds
- after 5 seconds
- after 10 seconds
- after 15 seconds

**Comment by Eejit43** [comment]
Nevermind, I finally understand what you meant!

**Comment by pjkaufman** [comment]
Is the setting something you would be interested in having added?

**Comment by Eejit43** [comment]
> Is the setting something you would be interested in having added?

I would definitely be interested in that, yes. I'd suggest having it default to a short amount of time, as I doubt many people have large vaults that take ages to lint. But, 100% up to you, and thanks!
