### ISSUE TITLE
Translation: Update `Quote Style` Name

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#769]
`Quote Style` translates to `报价风格`
should be translated as：`引用样式`  namely `citation style`

In addition, there is a special symbol `「」` for quotations in Chinese, can you add such an option?
example：`什么什么「引用样式」什么什么`

**Comment by pjkaufman** [comment]
I can make the update for the wording, but as for the addition of `「」`, I would need to know whether it is a single or double quote style and a name that it goes by in English so I can add it to the code as a variable.

**Comment by pjkaufman** [comment]
I see that you included a lot of information on when to use quotes, which is good to know. However `Quote Style` does not do anything with adding quotes that were not already present. It just updates a list of single quotes to what the selected option is and the same for double quotes. Single quotes for contractions are handled by themselves before dealing with other single quotes.

Thus all that is happening is a find and replace of existing.

As for `「」` and `『』`, I am not sure what their names are. I will see if I can find the quote style names since so far there are straight and smart quotes.

**Comment by pjkaufman** [comment]
I think I will call it [pinyin](https://en.wikipedia.org/wiki/Pinyin) since that is where it comes from according to [wikipedia](https://en.wikipedia.org/wiki/Quotation_mark) (sorry if this is incorrect as I am not sure where else to look for the naming and quotation styles).

**Comment by pjkaufman** [comment]
Do note that the Linter does not know the difference in languages so if you choose  `「」` and `『』` as your quote style. It will not differentiate between what to use in one file versus another.

**Comment by pjkaufman** [comment]
> It's a problem, it seems that the easiest way is for me to type the correct symbols when typing... In fact, these symbols Chinese mainland have discarded them.

To clarify, when you say `It's a problem`, are you saying that you don't want this feature added as the Linter does not distinguish between languages?

**Comment by pjkaufman** [comment]
I have added the the translation change to the Linter. I will break this into another issue for you for the potential addition of the Chinese citation style and see if there is a desire to get it added.

**Comment by pjkaufman** [comment]
@zhl111 , here is the related issue: https://github.com/platers/obsidian-linter/issues/771

I am closing this as part of the translation change and the other issue will count as the feature request.
