### ISSUE TITLE
Bug: "Move Math Block Indicators to Their Own Line" Not Working

### ISSUE THREAD

**Issue by songxiaocheng** [platers/obsidian-linter#783]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

The `Move Math Block Indicators to Their Own Line` rule did not work for simple cases and it seems related to incorrect `parseTextToAST` result.

## How to Reproduce

Example to reproduce issue with
```markdown
$$a$$

$$
b$$

$$c
$$
```

rule: `move-math-block-indicators-to-their-own-line`

## Expected Behavior

Expected output if applicable:

``` markdown
$$
a
$$

$$
b
$$

$$
c
$$
```

## ~~Screenshots~~ Current Output

``` markdown
$$
a
$$

$$
b$$

$$c
$$
```

## Device

- [x] Desktop

## Additional Context

In the function `makeSureMathBlockIndicatorsAreOnTheirOwnLines` in `mdast.ts`, there are `getPositions(MDAstTypes.Math, text)` and `getPositions(MDAstTypes.InlineMath, text)`. I printed the results, and it shows each has 1 element: it recognizes `$$a$$` as an **inline math**, which makes the rule accidentally worked, and it takes line 3-7, that is, the
```markdown
$$
b$$

$$c
$$
```
part as **one** math block, which makes the rule failed. See the console output below (the first array is by `MDAstTypes.Math` and the second one is by `MDAstTypes.InlineMath`).

<img width="408" alt="image" src="https://github.com/platers/obsidian-linter/assets/13874231/a76ba8b3-9d35-4f0a-a004-8f56da87cb25">

**Comment by pjkaufman** [comment]
@songxiaocheng , it looks like you have malformed math blocks back to back. The underlying package identifies the math blocks that I then work with. The math blocks are expected to either be inline math (i.e. start with values on the same line) or be a single math formula with values not on the same line as the opening and closing dollar signs.

That is to say, the underlying parser expects one of the two following formats.

Inline:
``` markdown
$$ math_here $$
```

Block:
``` markdown
$$
math_here
$$
```

I do not have control of the underlying parser and cannot change that behavior. Obsidian uses a different parser which I am unable to use since it is not made available and I don't have the time or skills to reverse engineer it.

That being said, I am curios where you are getting the math syntax you are using from. Could you reference which math format you are using? I use remark, so I can only reasonably parse remark math blocks.

**Comment by pjkaufman** [comment]
Note that I can try to parse these out by getting the opening dollar signs and then trying to split the text based on that, but I am not sure if math block nesting is valid or a thing. If it were, it would cause problems.

**Comment by pjkaufman** [comment]
Dev note: looks like nesting is not valid, so it may be possible to split math blocks based on opening dollar signs and then split it into groups based on that. However that results in the question of how to escape a dollar sign in a math block.

**Comment by pjkaufman** [comment]
That is because of how the parser works. It expects the dollar signs to be on their own lines. Normally there is another meaningful block between math equations besides a single paragraph which allows this issue to be avoided. I can probably just split the value of blocks based on the opening math block indicator and pair them up accordingly. However, that can cause bugs.

@songxiaocheng , are you implying that nesting math blocks is a thing when you said the following?
> @pjkaufman I did not expect to nest any equations.

**Comment by pjkaufman** [comment]
I can take a stab at this and see what happens. It just might get a little odd in some cases.

**Comment by pjkaufman** [comment]
I will hopefully get a chance to take a look at this later on this afternoon.

**Comment by pjkaufman** [comment]
I have started taking a look at this, but it is more in depth than I would like when it comes to the code for this. It will take a little while to see if I can get a proof of concept working.

**Comment by pjkaufman** [comment]
I believe that I have a simplistic fix for this scenario, but it may not work in more complex scenarios. For now, this should do the trick. But I would not rely on it figuring out how to properly determine multiple malformed math blocks back to back. It seems remark's parser for the math block scenarios can be finicky and not work as expected.

**Comment by pjkaufman** [comment]
It also looks like there is a max of 2 blocks that can be combined from my attempts to make more complex scenarios occur. So I have logic in place for the more blocks being combined, but I could not get it to actually happen in a way that made sense. So I will just go with what I have and we can proceed from there.

**Comment by pjkaufman** [comment]
I have merged the change for this into master and it should go out with the next release. Please let us know if it causes any problems.
