### ISSUE TITLE
FR: Wrap date strings into wikilink brackets

### ISSUE THREAD

**Issue by JulianDicken** [platers/obsidian-linter#809]
## Is Your Feature Request Related to a Problem? Please Describe.
I'm using the tasks plugin but want the inserted dates to be inserted as wikilinks, however they are inserted as plaintext dates only
## Describe the Solution You'd Like
The linter should recognise lone dates inside of file text and wrap dates inside wikilinks and wrap them into brackets

``` markdown
2023-07-19 Wednesday
```

``` markdown
[[2023-07-19 Wednesday]]
```

## Describe Alternatives You've Considered
PR for the tasks plugin, however I feel like this may be a linter type of usecase, generally speaking

**Comment by JulianDicken** [comment]
The linter should probably only validate against the date format specified, otherwise this might be hard to properly do

**Comment by pjkaufman** [comment]
Hey @JulianDicken , this sounds a lot like what custom commands are designed to handle. Have you tried setting up those?

**Comment by JulianDicken** [comment]
Right, forgot about those :)

**Comment by pjkaufman** [comment]
I am going to close this issue since I have not seen much activity around it.

If the dates follow a specific format like `YYYY-MM-DD day of week` then you could probably use [custom replacements/regex](https://platers.github.io/obsidian-linter/settings/custom-rules/#custom-regex-replacements) to make it so that they are converted to wiki links.
