### ISSUE TITLE
Bug: Has no effect on (())

### ISSUE THREAD

**Issue by jiajiala** [platers/obsidian-linter#850]
as the figure shows
![image](https://github.com/platers/obsidian-linter/assets/73203026/da2e123f-ce38-4b20-a9dc-dbc3e54aafa5)
When I use (()), (()) will not be eliminated

**Comment by pjkaufman** [comment]
@jiajiala , it lools like you are trying to use a unicode character in your regex. When you do, you need to use a `u` in the flags as well.

**Comment by pjkaufman** [comment]
Also note that you need to escape `(` and `)` using `\` if you intemd to match against them in the regex find.

**Comment by pjkaufman** [comment]
I plan to close this come Wednesday if I do not have a response.

A recap of the problem is that `(` and `)` have a special meaning in regex, so it needs to be escaped with `\`. So you would need to do something like the following regex for the find value: `\(\(OTHER_REGEX\)\)` should handle the scenario you are referring to. Please let us know if that does not work.

**Comment by pjkaufman** [comment]
Gotcha. In that case, I will close this come Wednesday.

**Comment by pjkaufman** [comment]
I am closing this issue since it seems to have been resolved.
