### ISSUE TITLE
Bug: Empty Array with Multi-Line

### ISSUE THREAD

**Issue by usernotnull** [platers/obsidian-linter#876]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

```
---
aliases: []
related: []
---
```

When forcing arrays to be multi-line. the "aliases" key is kept the same, but the "related" key changes, as below:

```
---
aliases: []
related:
  - 
---
```

The above is rendered as [null] in the Properties section.
This is problematic as the user is not able to edit the field anymore at all in obsidian Live Preview.

While this could be tackled as a bug in Obsidian, but technically this format means there is an empty item in an array, whereas [] is an empty array with no items.

A solution would be to make empty multi-line arrays rendered as [].

**Comment by RicSanOP** [comment]
ditto

**Comment by usernotnull** [comment]
In the Obsidian V1.4.11 release, the "null" issue has been resolved. 
However, this issue still stands as the default Obsidian way of dealing with an empty array is multi-line that reverts to [] when the array is empty.

**Comment by pjkaufman** [comment]
I will address the comments made here separately since they seem to be a little different from each other.

> In the Obsidian V1.4.11 release, the "null" issue has been resolved. However, this issue still stands as the default Obsidian way of dealing with an empty array is multi-line that reverts to [] when the array is empty.

It is good that the null issue has been resolved. I do not mind updating the default value for an empty multi-line array to be `[]`. However that may break the preservation of the YAML array types with some rules. Is that an acceptable trade off? I ask because there are some rules that try to preserve whatever the current key's format is, but that will not really be possible anymore for multi-line arrays since an empty array in the form of `[]` is always assumed to be a single-line array.
 
> I'm also wondering why are there 3 places for dealing with YAML array, 2 in the `General` settings related to "aliases" and "tags" and another in the `YAML` section for other keys. Shouldn't all properties be treated the same?

The reasons for the different places for the settings for YAML comes from 2 things: customization and reusability of the user specified format. Tags and aliases are special in Obsidian. They have their own special formats that are not really valid YAML array formats. To handle these formats (parsing and otherwise), it is necessary to have them be dealt with separately. They have extra options for what format they can be in (traditionally there are only single-line and multi-line arrays in YAML). As for why there are references to the tags and aliases format under general, that is because of how rules are handled. Each rule has its own settings. They do not naturally share settings (they are supposed to be independent of each other and be able to run by themselves without knowing anything about any other rules*). Thus when a lot of different rules started modifying the YAML frontmatter, there were requests to make it so that one place set the format used for aliases and tags so they did not have to make sure each rule had the tags and aliases format the exact same. Thus the settings were moved to the general section where manually created settings are placed. It could probably get moved to the YAML tab now (with some tweaking) since tabs were added after the addition of that setting.

Hopefully this helps understand how things got to be the way that they are today. It is a whole lot of things that just pile up over time when you develop. One choice dictates the next and it can cause a whole lot of trouble with backwards compatibility and usability to change where things are and how things work.

*: this is technically not true for YAML Key sort, but that one is the exception not the rule

**Comment by pjkaufman** [comment]
This should go out with the next release. Please let us know if there are any issues with this on master or in the next release.
