### ISSUE TITLE
FR: Lint on File Change should also lint when quitting Obsidian

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#897]
## Is Your Feature Request Related to a Problem? Please Describe.

Linting on file change only occurs when changing files, but I think it would be useful if linting prior to quitting was also part of this feature.

## Describe the Solution You'd Like

Lint before quitting as well as on file change. It seems logical that it would simply be part of the current feature, rather than as a sub-option to additionally enable.

## Describe Alternatives You've Considered

Remembering to manually save before quitting.

## Additional Context

If linting doesn't occur before quitting then linting only occurs the next time Obsidian opens and another file is changed to. Conceptually, it feels like the last step of a session was held over to the next session. For example, this isn't ideal for source control.

**Comment by pjkaufman** [comment]
Hey @redactedscribe , linting before quitting sounds like a nice addittion. However the hook for that is not garuanteed to run before the app closes, so it is not really worth all the bugs that will get reported when it does nkt finish before obsidian shuts down.

**Comment by pjkaufman** [comment]
Here is the link to the statement saying it may not actually be performed: https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L4615

**Comment by redactedscribe** [comment]
That's unfortunate. I wonder how unreliable it is in practice. A description under the option would help to reduce the number of filed bugs. What about on [`window-close`](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L4567) instead, or is it unrelated? Perhaps there is some creative solution such as introducing a dedicate button or keyboard shortcut which handles linting then quitting? I thought there might be a reason why it doesn't work like this already...

**Comment by pjkaufman** [comment]
Yeah. I looked into on quit when adding the feature. It might work for smaller files, but larger files would not work. It also would depend on how many other plugins are handling the quit even. It would also depend on how much time between the function getting called and when the app closes. File writes are delayed, so they likely would get ignored while the app quits.

Window close is likely for pop out windows, so that woupd not work from my understanding. I am guessing #392 is likely what would address this as well.
