### ISSUE TITLE
FR: (How to) Add custom misspelling autocorrection rules (?)

### ISSUE THREAD

**Issue by zanodor** [platers/obsidian-linter#915]
Hello there,

I searched the issues for a similar request and found none.  

## Is Your Feature Request Related to a Problem? Please Describe.

I was hoping to find some info about this in the Wiki. Found none. I write bilingually; I'd like to add my own BadWord -- GoodWord dictionary.

## Describe the Solution You'd Like

Make the file editable. On install of the plugin, the txt or json file would be downloaded and freely editable.  
Alternatively, make the user able to add their own txt or json file that would 1) either override the plugin's own solution 2) or would coexist with it.  
In the Various Complements plugin, one can add multiple dictionaries (but has no autocorrection capabilitles).  

## Describe Alternatives You've Considered

Currently, I have multiple dictionaries on in Obsidian, and my text is red all over as I do etymologies and etymons, so it's impossible to tell the difference from a typo or a legit, say "Hottentottese" word.  
I have not tried any other service. Actually, BadWord -- GoodWord lists are hard to come by as well. (Would like some advice as well from someone.)

Thanks for considering my request,

All the best

**Comment by pjkaufman** [comment]
Hey @zanodor , this is definitely an interesting request. At this time the Linter does not support this operation and it would take some work to make this possible, so the Linter likely won't support this any time soon without a desire from the community to get it added or someone else writing this functionality.

When you say there is a "BadWord -- GoodWord" list, the first thing that comes to mind to me is the custom replace logic in the Linter. You can specify the word to find (case sensitive) with the value to replace it with. That seems to me like the best option for you within the bounds of the Linter unless you personally know how to code JavaScript or would be willing to learn some.

Here is an example of some find and replace values you could use:
| Find | Replace | Flags |
| ------ | ----------- | -------- |
| ([Aa])lgor | $1lgo | gm |
| ([Ww])od | $1ord | gm |

Notice that the regex capture group should handle both the capitalized and capitalized versions of the words automatically. Do note that there may be a better way, but this is just my first impression based on what you have said. This could get unruly if you are trying to create a large list. This would be a list you would need to maintain since the list the Linter uses is meant for English, but it does bleed over into some other languages.

**Comment by pjkaufman** [comment]
Depending upon the languages you use it may be possible to find some online, but I do not have any lists that I have built myself. The only list included in the Linter comes from [codespell](https://github.com/codespell-project/codespell). It is a general auto correct system, but I am not sure it cares which language you are using.
Their dictionaries are located [here](https://github.com/codespell-project/codespell/tree/master/codespell_lib/data), but they are mostly in English. You might be able to use Codespell manually via the CLI and use a custom dictionary if someone has one out there for the languages you are looking for.

**Comment by pjkaufman** [comment]
Gotcha. I am going to close this since it sounds like there is nothing to be done about this.
