### ISSUE TITLE
FR: Two spaces after each period.   

### ISSUE THREAD

**Issue by CGPGrey** [platers/obsidian-linter#948]
I am one of the (apparently) rare users who still prefers two spaces after each period.   Can I request an option to format all text in a document to match this style?

**Comment by pjkaufman** [comment]
> I am one of the (apparently) rare users who still prefers two spaces after each period. Can I request an option to format all text in a document to match this style?

Hey @CGPGrey , if you just want 2 spaces after a period then that is feasible via custom replace under the custom settings tab. You would use `\. ?([^ ])` as the regex to find and `.  $1` as the replace value. Leave `gm` as the flags and it should be taken care of.

What does the regex and replace described above do?
It looks for a period followed by a single space or no space at all and adds 2 spaces after it (test it on a dummy note first to verify it works since I just cobbled it together from memory).
This should take care of it. But if not please let me know.

Note: this will affect tables, inline and code blocks, inline and math blocks, YAML etc.

**Comment by pjkaufman** [comment]
I am closing this due to a lack of feedback on whether the suggested regex works.
