### ISSUE TITLE
Question: On Lint on Save and the breaking of Templater scripts

### ISSUE THREAD

**Issue by zanodor** [platers/obsidian-linter#994]
Hey there,

My question is about the purpose of ignored folders and lint on save.  

Not for the first time -- probably about the 3rd or 4th time -- I inadvertently linted Templater files. Which means I had YAML created with date modified key and value and soft line breaks on each line. Neither are very beneficial, to say the least. It breaks one's template (I'm using Templater js to carry out small daily janitor jobs, so these are not really templates, but bits of code).  

Last time around, I probably hit CNTRL + S or linted one of my templates I was editing and had the offending changes happening.  

Then I realized that -- after having had to switch off 'lint file change' as you may remember the other thread -- I'd be better off switching off 'lint on save' as well.  
As a workaround, I added the hotkey CNTRL + S for 'lint current file unless ignored'.  
Goes without saying the template folder is among those on the list of ignored folders.  

At this point, my question actually turns into a suggestion: would you consider adding support for:  
1. turning 'lint on save' to 'lint on save unless ignored' (or adding the new one as a second option one could tick);  
2. providing some other means of security for people using Templater in some way?

I'm guessing No 1. would be more feasible to achieve.  

Thanks a lot

Regards,
Z.

**Comment by pjkaufman** [comment]
I am not 100% sure what is happening here since I have used this plugin for years now and have not hit the issue where I have linted Templater files since I added them to my ignore path.

So I would like to better understand the problem since I believe that, except for manually telling a file to be linted, it should be checking that the file is a markdown file and that it is not ignored.

How are you currently able to lint your Templater files if they are in your ignored path? It may be a bug in the Linter unless you are using the rule/logic that is meant to bypass that.

**Comment by pjkaufman** [comment]
I did double check the logic and there is some logic in place to make sure that lint on file change does not run on ignored files. So if it is running on them, that would be a bug that needs fixing.

**Comment by pjkaufman** [comment]
Note: Lint on save is checking that the file is a markdown file and that it is ignored.

I am not sure how you are linting ignored folders (not sure if that is where your Templater scripts live), but if they do, a reproducible example would help greatly in getting to the bottom of this.

Thanks!

**Comment by pjkaufman** [comment]
No worries. The commander macro can use lint unless ignored and that should take care of it.

I am glad this is fixed for you!
